### ISSUE TITLE
Not rebooting on schedule

### ISSUE THREAD

**Issue by desreela** [weaveworks/kured#105]
Hi,

I have kured configured to run the reboots only during the weekends in Azure Kubernetes Service. However it's not rebooting the nodes during the weekend even after the /var/run/reboot-required file is created 8 days ago. 
I am using the image tag:master-4beddb5 as i could find it as the only one supporting --reboot-days switch. 

Daemonset Config:
-----------------------
        - name: kured
          image: docker.io/weaveworks/kured:master-4beddb5
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true # Give permission to nsenter /proc/1/ns/mnt
          env:
            # Pass in the name of the node on which this pod is scheduled
            # for use with drain/uncordon operations and lock acquisition
            - name: KURED_NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          command:
            - /usr/bin/kured
            - --period=18h
            - --reboot-days=su,sa
            - --reboot-sentinel=/var/run/reboot-required
-----------------------

all the kured pod logs show:
----------------------------
kubectl logs kured-n77fd -n kube-system
time="2019-12-15T18:48:24Z" level=info msg="Kubernetes Reboot Daemon: master-4beddb5"
time="2019-12-15T18:48:24Z" level=info msg="Node ID: aks-aksdeploy-21345136-vmss000001"
time="2019-12-15T18:48:24Z" level=info msg="Lock Annotation: kube-system/kured:weave.works/kured-node-lock"
time="2019-12-15T18:48:24Z" level=info msg="Reboot Sentinel: /var/run/reboot-required every 18h0m0s"
time="2019-12-15T18:48:24Z" level=info msg="Blocking Pod Selectors: []"
time="2019-12-15T18:48:24Z" level=info msg="Reboot on: Sun---------------Sat between 00:00 and 23:59 UTC"
---------------------------

The nodes are up and running for more than 8 days and the /var/run/reboot-required file is created 8 days ago.  
Any configuration missing here? how to check for additional logs?

Regards,

**Comment by mmisztal1980** [comment]
We've set up kured using tag: `master-f6e4062`

Kured is set execute reboots in the following time-window: `00:00 - 04:00` daily, using the following set of overrides to supplement it's regular `values.yaml` :

```yaml
extraArgs:
  start-time: 00:00
  end-time: 04:00
  time-zone: Europe/Copenhagen
serviceAccount:
  create: true
  name: kured
updateStrategy: RollingUpdate
```

We've executed `sudo touch /var/run/reboot-required` on one of the cluster nodes to verify the reboot functionality.

This is the stdout output of the pod running on the node containing the `/var/run/reboot-required`.

```
time="2020-02-20T23:32:51Z" level=info msg="Kubernetes Reboot Daemon: master-f6e4062"
time="2020-02-20T23:32:51Z" level=info msg="Node ID: aks-agentpool-18189453-vmss000001"
time="2020-02-20T23:32:51Z" level=info msg="Lock Annotation: kured/kured:weave.works/kured-node-lock"
time="2020-02-20T23:32:51Z" level=info msg="Reboot Sentinel: /var/run/reboot-required every 1h0m0s"
time="2020-02-20T23:32:51Z" level=info msg="Blocking Pod Selectors: []"
time="2020-02-20T23:32:51Z" level=info msg="Reboot on: SunMonTueWedThuFriSat between 00:00 and 04:00 Europe/Copenhagen" time="2020-02-20T23:32:52Z" level=info msg="Holding lock"
time="2020-02-20T23:32:52Z" level=info msg="Uncordoning node aks-agentpool-18189453-vmss000001"
time="2020-02-20T23:32:54Z" level=info msg="node/aks-agentpool-18189453-vmss000001 uncordoned" cmd=/usr/bin/kubectl std=out
time="2020-02-20T23:32:54Z" level=info msg="Releasing lock"
time="2020-02-21T00:21:36Z" level=info msg="Reboot not required"
time="2020-02-21T01:21:36Z" level=info msg="Reboot not required"
time="2020-02-21T02:21:36Z" level=info msg="Reboot not required"
```

I don't see any indication that kured has rebooted the node - unless I'm mistaken..?

**Comment by remiserriere** [comment]
Hi, 
I've also had the same issue when we first configured scheduled reboots using the 1.2.0 release, using image tag f6e4062 fixed that.

**Comment by evrardjp** [comment]
Thanks for the feedback @remiserriere . Do you think we should close this now?

**Comment by suresh8771** [comment]
I too looking for 
1. changing  the frequency of check for /var/run/reboot-required 
2. Validating Kured deployment on AKS cluster by rebooting one of the node by creating /var/run/reboot-required file ( not sure how to achieve this)
