### ISSUE TITLE
Kured helm chart references invalid bitnami/kubectl tag

### ISSUE THREAD

**Issue by jrryjcksn** [weaveworks/kured#108]
See issue: https://github.com/helm/charts/issues/20433

**Comment by dholbach** [comment]
Looks like `autolock` was introduced in the Helm chart through https://github.com/helm/charts/pull/17246 - the discussion back then was not uncontroversial.

**Comment by dholbach** [comment]
There's neither `bitnami` nor `autolock` mentions in `kured` master.

**Comment by mtparet** [comment]
cf https://github.com/helm/charts/pull/20841 we should close the issue here.

**Comment by dholbach** [comment]
Thanks for the pointer @mtparet
