### ISSUE TITLE
verification of version compatibility

### ISSUE THREAD

**Issue by pniederlag** [weaveworks/kured#116]
In the version compatibilty 1.3.0 is marked as shipping kubectl 1.15.x and being compatible with kubernetes 1.15, 1.16 and 1.17. 
Also it is stated that

>  Kubernetes aims to provide forwards & backwards compatibility of one minor version between client and server:

If kured 1.3.0 ships kubectl 1.15.x, shouldn't it be compatible with 1.14, 1.15 and 1.16?

https://github.com/weaveworks/kured/blob/master/README.md#kubernetes--os-compatibility

**Comment by pniederlag** [comment]
Installation of kured 1.3.0 worked flawless on an AKS based kubernetes cluster with 1.14.8.

Now testing via `sudo touch /var/run/reboot-required` wether reboot will be performed as set by schedule

**Comment by evrardjp** [comment]
I sure hope your cluster rebooted since that previous comment! Could you push an update to the documentation, to mention to extra support? That would be lovely.

**Comment by pniederlag** [comment]
Until now we have seen kured 1.3.0 to be working with ASK 1.14.8.

**Comment by evrardjp** [comment]
That's good news :)
