### ISSUE TITLE
Clean up notifications system and implement generic notifications

### ISSUE THREAD

**Issue by evrardjp** [weaveworks/kured#117]
Hello folks,

I've noticed that there are multiple PRs for notifications (see [1] and [2]), and I wonder if we shouldn't instead just write a generic notification system. This would avoid proliferation of ``<insert my favorite notification tool here>``, at the expense of not having "everything bundled" into kured directly.

I would like to have feedback before starting to write this.

The idea would be to remove the arguments slack-hook-url, slack-username, and introduce a generic "notification-cmd" cli argument. The argument could be a string which can be used to call a command. That command would replace ``%{severity}``, ``%{node}``, ``%{msg}``, ``%{action}`` by severity, nodeID, message, and action taken by cured.

This allows a very simple replacement, which works for everyone, whether it's a command or a webservice. This is disruptive for current slack notifications users: Slack users would need a client which handles the notifications in the container. This could be delivered by the kured community separately.

I thought this was a very clean separation of concerns: One core code, and one notification client.

@dholbach what's your opinion?

[1]: https://github.com/weaveworks/kured/pull/64
[2]: https://github.com/weaveworks/kured/pull/49

**Comment by evrardjp** [comment]
That would also help on https://github.com/weaveworks/kured/issues/47#issuecomment-537041883 , on https://github.com/weaveworks/kured/pull/49 .

**Comment by simskij** [comment]
Hey,

[Shoutrrr](https://github.com/containrrr/shoutrrr) maintainer here.

Let me know if I can be of any use, if you ever decide to go down the route suggested in #94. The aim of the shoutrrr project is to provide something similar to [caronc/apprise](https://github.com/caronc/apprise), but in go, allowing projects to focus on the things that add value for them, rather than duplicating efforts on solved problems.

Thanks 🙏🏼

**Comment by atighineanu** [comment]
> Hey,
> 
> [Shoutrrr](https://github.com/containrrr/shoutrrr) maintainer here.
> 
> Let me know if I can be of any use, if you ever decide to go down the route suggested in #94. The aim of the shoutrrr project is to provide something similar to [caronc/apprise](https://github.com/caronc/apprise), but in go, allowing projects to focus on the things that add value for them, rather than duplicating efforts on solved problems.
> 
> Thanks 🙏🏼

Tried it. It looks indeed nice. 
https://github.com/weaveworks/kured/pull/228
