### ISSUE TITLE
Error: unknown flag: --time-zone

### ISSUE THREAD

**Issue by d-kukharenko** [weaveworks/kured#120]
Version : 1.3.0

Expected behavior: Adding --time-zone argument to KURED sets the given timezone.

Actual behavior: Adding --time-zone argument causes KURED to fail on start.

Details:
I have my KURED set up from Terraform 

`resource "helm_release" "kured" {`
` name          = "kured"`
  `chart         = "stable/kured"`
  `repository    = "${var.QUAY_HELM_CONTAINER_REGISTRY}"`
  `version       = "${var.KURED_HELM_CHART_VERSION}"`
  `namespace     = "kube-system"`
  `recreate_pods = true`
  `depends_on    = ["null_resource.helm_repo_update", "azurerm_kubernetes_cluster.k8s"]`

  `values = [<<EOF`
  `image:`
    `repository: "${var.DOCKER_CONTAINER_REGISTRY}/weaveworks/kured"`
  `extraArgs:`
    `slack-hook-url: ${var.KURED_SLACK_HOOK_URL}`
    `slack-username: ${var.apmid}-${var.envshort}`
    `time-zone: ${var.KURED_TIME_ZONE}`
`EOF`
  `]`
`}`

Which have worked perfectly fine, until I added the time-zone argument.
Now the pod enters the crash-lopp back-off with the next logs
![image](https://user-images.githubusercontent.com/62420884/77147637-5f9d3b80-6a96-11ea-9b7a-bcbf10ceff25.png)

[README](https://github.com/weaveworks/kured/blob/master/README.md) states that the argument is available, but error logs has no mention of it in suggested valid arguments list.

**Comment by ckotzbauer** [comment]
Hi,
which version of the helm-chart you are using? Is the problem still there?

**Comment by d-kukharenko** [comment]
Hi, 
We were using the 2.14.3 Helm.
I can't update you on the presence of the problem because we removed that parameter since it was failing the pod.

**Comment by ckotzbauer** [comment]
Ok. Could you do a `helm list` and share the kured-line that I can see which version is installed?
Which value is stored in `var.KURED_HELM_CHART_VERSION` from terraform?

**Comment by d-kukharenko** [comment]
1.2.0

**Comment by ckotzbauer** [comment]
No, problem ;)
That's too old. The feature was introduced in kured `1.3.0` which was released with the chart-version `1.5.0`.
https://github.com/helm/charts/commit/9eebe0ec905e473ec210299b8b6ef912a9816e7a#diff-5a6820d741e49d11f5a77dad4abfb560

**Comment by d-kukharenko** [comment]
Ok, gotcha.
We will test with a new chart version, thanks.

**Comment by dholbach** [comment]
Can you test https://github.com/weaveworks/kured/tree/master/charts/kured?

**Comment by d-kukharenko** [comment]
I've put it in our backlog for the next sprint, probably will do in a week or two, I'll share the updates as soon as we get results.

**Comment by dholbach** [comment]
Excellent - thanks @d-kukharenko !

**Comment by davidkarlsen** [comment]
@d-kukharenko did it work out - can we close this?
