### ISSUE TITLE
Implement configurable sentinel/reboot commands

### ISSUE THREAD

**Issue by evrardjp** [weaveworks/kured#122]
I checked a few issues/PR, I can only notice that establishing a configurable sentinel and reboot command (see [1]) would allow us to close a few other issues and PR:
- https://github.com/weaveworks/kured/issues/26
- https://github.com/weaveworks/kured/issues/4
- https://github.com/weaveworks/kured/pull/77
- https://github.com/weaveworks/kured/issues/23#issuecomment-410443836
- https://github.com/weaveworks/kured/issues/31
- https://github.com/weaveworks/kured/pull/43
- https://github.com/weaveworks/kured/issues/44
- https://github.com/weaveworks/kured/issues/59

[1]: https://github.com/weaveworks/kured/blob/834e7d191d029c733930eb561e3f40ace470d8a3/cmd/kured/main.go#L264

**Comment by stuartpb** [comment]
If you're gathering use cases, I'll note that Kubic has a wide variety of alternatives to `kured`, like `kexec`: https://kubic.opensuse.org/documentation/man-pages/transactional-update.conf.5.html

**Comment by smueller18** [comment]
I have another use case for my cluster. Whenever kured reboots a node, the default alerts for ceph storage pods are firing for some minutes until the pods are ready again after the reboot.
The [`amtool`](https://github.com/prometheus/alertmanager/tree/master/cmd/amtool) binary can be used to silence alertmanager alerts. An example command to silence an alert is

```
amtool --alertmanager.url="http://localhost:9093" silence add --duration="30m" --author="kubernetes" --comment="reboot host" alertname="MyAlertName" host="$HOST"
```
It would be nice, if kured offers the ability to run such kinds of commands right before the reboot command is triggered.

I already though about alternatives, but none of them works:

- [`PreStop`](https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/#container-hooks) of kured pod hook executes `amtool`: runs always when the pod is terminated, not only on reboots by kured
- executes `amtool` by a systemd service on the host: not native kubernetes and runs also if not triggered by kured

**Comment by evrardjp** [comment]
> If you're gathering use cases, I'll note that Kubic has a wide variety of alternatives to `kured`, like `kexec`: https://kubic.opensuse.org/documentation/man-pages/transactional-update.conf.5.html

These seem to be the target of a transactional update action, which means that transactional update action can call kured, and if kured is configured to call kexec, that would work... Sounds a tad complex though :)

**Comment by evrardjp** [comment]
Curently stale, but we should keep this issue opened, as it's the way to track all the sub issues.

We just have prioritized the testing first.

**Comment by anthr76** [comment]
kexec would be great! Any thoughts from a maintainer on opening this back up?

**Comment by evrardjp** [comment]
It's not only about kexec... !

But guess what?! It's implemented in our main branch (See also https://github.com/weaveworks/kured/pull/297) ! It will be available on the next release, which should happen soon!
