### ISSUE TITLE
use kubectl/pkg/drain instead of binary

### ISSUE THREAD

**Issue by alexeldeib** [weaveworks/kured#124]
(didn't see an existing issue)

There's been a lot of great work to extract the drain logic to https://github.com/kubernetes/kubectl/blob/master/pkg/drain/drain.go

We could take advantage of this programmatically and remove the kubectl binary from the docker image.

**Comment by dholbach** [comment]
Could https://github.com/weaveworks/wksctl/pull/271 serve as example code here?

**Comment by luxas** [comment]
yes :+1:

**Comment by evrardjp** [comment]
@atighineanu are you interested by working on this?
