### ISSUE TITLE
Suggestion: Add who is sending the alert from where when using slack

### ISSUE THREAD

**Issue by jonaspetersorensen** [weaveworks/kured#125]
Example today:
> Draining node aks-nodepool1-35951703-vmss00000b
> Rebooting node aks-nodepool1-35951703-vmss00000b

When you have multiple components that send alerts to slack then messages like these turn into a guessing game for who did what where. Add more clusters into the mix and it can get quite confusing.

Suggestion:
> kured is draining node aks-nodepool1-35951703-vmss00000b in cluster please-work-10
> kured is rebooting node aks-nodepool1-35951703-vmss00000b in cluster please-work-10

**Comment by adhodgson1** [comment]
You can use the --slack-username parameter to override the notification user, I have been doing this for ages with the cluster name as this parameter and it works well.

**Comment by SirBrecilos** [comment]
settings slack-username does not seem to work for me
Tried setting it via configuration & extraArgs object

Any suggestions?
```
helm get values kured:
  configuration:
    slackUsername: prod
  extraArgs:
    slack-username: prod
```

**Comment by DaniJG** [comment]
When using the new recommended webhook approach in slack (creating an app and adding incoming webhooks as per https://api.slack.com/messaging/webhooks), each webhook URL is statically associated with a username and a channel.
Directly from their docs
