### ISSUE TITLE
Testing KureD on AKS Cluster and Frequency of Reboots on AKS?

### ISSUE THREAD

**Issue by jyee021** [weaveworks/kured#128]
We have a lab cluster sitting in AKS that has had the KureD daemon set running on it since March 10, about 20 days ago, but haven't gotten any reboot messages.  Does anyone know how often nodes do need to be rebooted on AKS? And does KureD log when it does reboot a node? Is SSH into the VMSS the only way to trigger a test?

time="2020-03-10T16:31:29Z" level=info msg="Kubernetes Reboot Daemon: 1.3.0"
time="2020-03-10T16:31:29Z" level=info msg="Node ID: aks-XXXX-XXXXXX-vmssXXXX"
time="2020-03-10T16:31:29Z" level=info msg="Lock Annotation: kube-system/kured:weave.works/kured-node-lock"
time="2020-03-10T16:31:29Z" level=info msg="Reboot Sentinel: /var/run/reboot-required every 12h0m0s"
time="2020-03-10T16:31:29Z" level=info msg="Blocking Pod Selectors: []"
time="2020-03-10T16:31:29Z" level=info msg="Reboot on: SunMonTueWedThuFriSat between 19:00 and 07:00 America/New_York"

**Comment by ritazh** [comment]
cc @alexeldeib can you pls help take a look?

**Comment by jyee021** [comment]
Latest set of logs
time="2020-04-01T13:28:12Z" level=info msg="Kubernetes Reboot Daemon: 1.3.0"
time="2020-04-01T13:28:12Z" level=info msg="Node ID: aks-XXXXX-XXXXXX-vmss000000"
time="2020-04-01T13:28:12Z" level=info msg="Lock Annotation: kube-system/kured:weave.works/kured-node-lock"
time="2020-04-01T13:28:12Z" level=info msg="Reboot Sentinel: /var/run/reboot-required every 12h0m0s"
time="2020-04-01T13:28:12Z" level=info msg="Blocking Pod Selectors: []"
time="2020-04-01T13:28:12Z" level=info msg="Reboot on: SunMonTueWedThuFriSat between 19:00 and 07:00 America/New_York"

Is there anyway to confirm whether a reboot has occurred?

**Comment by lgmorand** [comment]
@jyee021 reboot only occurs when a patch is applied and this patch **requires** reboot. Not so often. Patchs are applied on daily basis on linux nodes
If you want to test it manually, SSH to one of your nodes and create an empty file /var/run/reboot-required

Reboot will occur for sure

**Comment by johnjbateman** [comment]
@lgmorand I am also running on AKS and never see any logs about a reboot or even that it checks for them.  Been running 9 days now.  I also see that my kured pods have 70* restarts each.  Is that normal?

**Comment by lgmorand** [comment]
that's not normal, could you check the flags of kured ? MIne is configured to reboot only on Mon.Tue

`helm install kured stable/kured --namespace kured --set nodeSelector."beta\.kubernetes\.io/os"=linux,extraArgs.reboot-days="Mon\,Tue"`

> lgmorand@DESKTOP-RT46CFU:$ k get po -n kured
NAME          READY   STATUS    RESTARTS   AGE
kured-598zx   1/1     Running   1          2d1h
kured-5s8k5   1/1     Running   3          2d1h
lgmorand@DESKTOP-RT46CFU:~$ k logs kured-598zx -n kured
time="2020-05-12T15:11:59Z" level=info msg="Kubernetes Reboot Daemon: 1.3.0"
time="2020-05-12T15:11:59Z" level=info msg="Node ID: aks-appnodepool-17697912-vmss000000"
time="2020-05-12T15:11:59Z" level=info msg="Lock Annotation: kured/kured:weave.works/kured-node-lock"
time="2020-05-12T15:11:59Z" level=info msg="Reboot Sentinel: /var/run/reboot-required every 1h0m0s"
time="2020-05-12T15:11:59Z" level=info msg="Blocking Pod Selectors: []"
time="2020-05-12T15:11:59Z" level=info msg="Reboot on: ---MonTue------------ between 00:00 and 23:59 UTC"
time="2020-05-12T15:11:59Z" level=info msg="Holding lock"
time="2020-05-12T15:11:59Z" level=info msg="Uncordoning node aks-appnodepool-17697912-vmss000000"
time="2020-05-12T15:12:00Z" level=info msg="node/aks-appnodepool-17697912-vmss000000 uncordoned" cmd=/usr/bin/kubectl std=out
time="2020-05-12T15:12:00Z" level=info msg="Releasing lock"
time="2020-05-12T16:41:11Z" level=info msg="Reboot not required"
time="2020-05-12T17:41:11Z" level=info msg="Reboot not required"
time="2020-05-12T18:41:11Z" level=info msg="Reboot not required"
time="2020-05-12T19:41:11Z" level=info msg="Reboot not required"
time="2020-05-12T20:41:11Z" level=info msg="Reboot not required"
time="2020-05-12T21:41:11Z" level=info msg="Reboot not required"
time="2020-05-12T22:41:11Z" level=info msg="Reboot not required"
time="2020-05-12T23:41:11Z" level=info msg="Reboot not required"

**Comment by johnjbateman** [comment]
@lgmorand We install with a ds, so here is the snippet:

```
          command:
            - /usr/bin/kured
#            - --alert-filter-regexp=^RebootRequired$
#            - --blocking-pod-selector=runtime=long,cost=expensive
#            - --blocking-pod-selector=name=temperamental
#            - --blocking-pod-selector=...
            - --ds-name=kured
            - --ds-namespace=kube-system
            - --end-time=6:59:59
            - --lock-annotation=weave.works/kured-node-lock
            - --period=1h
#            - --prometheus-url=http://prometheus-k8s.monitoring.svc.cluster.local:9090
            - --reboot-days=sun,mon,tue,wed,thu,fri,sat
            - --reboot-sentinel=/var/run/reboot-required
#            - --slack-hook-url=https://hooks.slack.com/...
#            - --slack-username=prod
#            - --slack-channel=alerting
            - --start-time=0:00
            - --time-zone=America/New_York
```

**Comment by lgmorand** [comment]
I'm not an expert, but three times the same flag (blocking pod), are you sure, it's supported ?
you are overriding default values with the same values (i.e. period, reboot days, etc). IMHO, I prefer to stick to only add different flags, not default ones

What are saying the logs of your pods ?

Helm install also install DS ;-)

**Comment by lgmorand** [comment]
maybe do a default install, test it. if it's fine, then add the flag one by one, to find the culprit, but at least test a vanilla installation

**Comment by johnjbateman** [comment]
The default from the get repo had things commented out '#' so those three are commented out:

```
#            - --alert-filter-regexp=^RebootRequired$
#            - --blocking-pod-selector=runtime=long,cost=expensive
#            - --blocking-pod-selector=name=temperamental
#            - --blocking-pod-selector=...
```

Sure I can try one at a time.  Thanks!

**Comment by johnjbateman** [comment]
The log of my pod:

```
time="2020-05-14T10:58:59Z" level=info msg="Kubernetes Reboot Daemon: 1.4.0"
time="2020-05-14T10:58:59Z" level=info msg="Node ID: aks-nodepool1-11458102-vmss000000"
time="2020-05-14T10:58:59Z" level=info msg="Lock Annotation: kube-system/kured:weave.works/kured-node-lock"
time="2020-05-14T10:58:59Z" level=info msg="Reboot Sentinel: /var/run/reboot-required every 1h0m0s"
time="2020-05-14T10:58:59Z" level=info msg="Blocking Pod Selectors: []"
time="2020-05-14T10:58:59Z" level=info msg="Reboot on: SunMonTueWedThuFriSat between 00:00 and 06:59 America/New_York"
```

**Comment by lgmorand** [comment]
that's weird. and you say your pod id often rebooted ?
in my case, 1 restart within 3 days for one, 3 restart for the other one

one seems in the same state than you

> time="2020-05-14T06:32:33Z" level=info msg="Kubernetes Reboot Daemon: 1.3.0"
time="2020-05-14T06:32:33Z" level=info msg="Node ID: aks-nodepool1-17697912-vmss000000"
time="2020-05-14T06:32:33Z" level=info msg="Lock Annotation: kured/kured:weave.works/kured-node-lock"
time="2020-05-14T06:32:33Z" level=info msg="Reboot Sentinel: /var/run/reboot-required every 1h0m0s"
time="2020-05-14T06:32:33Z" level=info msg="Blocking Pod Selectors: []"
time="2020-05-14T06:32:33Z" level=info msg="Reboot on: ---MonTue------------ between 00:00 and 23:59 UTC"

**Comment by johnjbateman** [comment]
Correct, each pod showed over 70 restarts.  I have no idea if the node rebooted, but I doubt it

**Comment by jyee021** [comment]
@johnjbateman - I worked around the SSH issue by creating a pod that mounted a volume to the host node and then I was able to manually create the sentinel value by running a shell into the pod.  I did notice if you run the daemon set with the default settings, there is an hourly (default is it checks every hour) message that gets logged about it checking for a necessary reboot, but once you set specific flags those messages go away.  I have it run every 12 hours and don't see a message every 12 hours that it checked for a reboot.  I only see a pod restart when a reboot has occurred, if the pod is crashing and restarting, you may want to check that those pods are not being evicted for other reasons like resource constraints...

**Comment by johnjbateman** [comment]
strange, it looks like from my reboot window, 12-7AM, the pods restarted 6-7 times, so I am assuming they attempt the reboot check or reboot and they crash.  I have no logs in the pods cause I have new pods up now.

```
NAME                                        READY   STATUS    RESTARTS   AGE
kured-2lkss                                 1/1     Running   6          22h
kured-l859r                                 1/1     Running   7          22h
kured-pqjz4                                 1/1     Running   6          22h
kured-xx2q9                                 1/1     Running   6          22h
kured-xx4q8                                 1/1     Running   6          22h
```

Current logs:

```
time="2020-05-15T10:13:45Z" level=info msg="Kubernetes Reboot Daemon: 1.3.0"
time="2020-05-15T10:13:45Z" level=info msg="Node ID: aks-nodepool1-11458102-vmss000002"
time="2020-05-15T10:13:45Z" level=info msg="Lock Annotation: kube-system/kured:weave.works/kured-node-lock"
time="2020-05-15T10:13:45Z" level=info msg="Reboot Sentinel: /var/run/reboot-required every 1h0m0s"
time="2020-05-15T10:13:45Z" level=info msg="Blocking Pod Selectors: []"
time="2020-05-15T10:13:45Z" level=info msg="Reboot on: SunMonTueWedThuFriSat between 00:00 and 06:59 America/New_York"
```

**Comment by lgmorand** [comment]
6 times withing 24hrs is a lot. Maybe you could have a monitoring solution grabbing the stdout & stderr. there may be a way to capture the logs of the pods, and then read them even if they crashed.
Are you using Azure Monitor ? You should enable it, then a query could be like this

`let startTime = ago(3d);
let containerLogs = ContainerLog
| where TimeGenerated > startTime
| where _IsBillable == true
| summarize BillableDataMBytes = sum(_BilledSize)/ (1000. * 1000.) by LogEntrySource, ContainerID;
let kpi = KubePodInventory
| where TimeGenerated > startTime
| distinct ContainerID, Namespace;
containerLogs
| join
    kpi
on $left.ContainerID == $right.ContainerID
| extend sourceNamespace = strcat(LogEntrySource, "/", Namespace)
| summarize MB=sum(BillableDataMBytes) by sourceNamespace
| render piechart`

**Comment by johnjbateman** [comment]
Good call!  My EFK stack was down and was recently fixing it.  Pulled up kibana and presto:

```
time="2020-05-15T10:59:19Z" level=fatal msg="Error acquiring lock: daemonsets.apps \"kured\" is forbidden: User \"system:serviceaccount:kube-system:kured\" cannot update resource \"daemonsets\" in API group \"apps\" in the namespace \"kube-system\""
```

Fixing...
