### ISSUE TITLE
How to troubleshoot "Lock already held" issue?

### ISSUE THREAD

**Issue by wasker** [weaveworks/kured#137]
Hi all,

When I inspect kured logs, they're full of messages like below, without any additional information. How to debug the reason the node isn't getting rebooted?

```
time="2020-04-28T14:59:28Z" level=warning msg="Lock already held: aks-nodepool1-37267398-vmss000009"
time="2020-04-28T15:59:28Z" level=info msg="Reboot required"
```

**Comment by wasker** [comment]
After meditating on this message for some time, I noticed that it refers to a node that doesn't exist anymore. Another potential contributor to the problem was the fact that we had 1 node in cluster. Once I manually cleared up the lock and added another node, reboots are working.

Having unblocked myself, I wonder if kured could detect potentially blocking situations like:

* Lock is held on a node that doesn't exist
* Not enough nodes in cluster to reboot the one

...and put that in the log.

**Comment by ericsuhong** [comment]
We also faced the same issue where kured was stuck in "Lock already held: xxx node", but this xxx node was already removed and gone from kubernetes system.

Shouldn't kured has some kind of timeout on the lock to avoid this "ghost node" lock holding forever situation?

**Comment by wasker** [comment]
Looks like `--annotation-ttl` is [the feature](https://github.com/weaveworks/kured#automatic-unlock).

**Comment by ericsuhong** [comment]
Thanks for the pointer. Seems like this is a new feature that has been recently added and not included in the latest release yet. We will wait for a newer release that include this feature after it is tested thoroughly.

**Comment by evrardjp** [comment]
Can we close this?

**Comment by wasker** [comment]
Yes, this can be closed.

**Comment by arusa** [comment]
In my case kured somehow "forgot" to uncordon the node and remove the lock. After manual uncordon the lock did still exist, so I'm adding the information here how to manually remove all locks:

```
kubectl -n kube-system annotate ds kured weave.works/kured-node-lock-
```

_This will remove the annotation on the DaemonSet and I advise to first check the content of that annotation._

Found here: https://kured.dev/docs/operation/
