### ISSUE TITLE
Move official Helm-Chart to this repo

### ISSUE THREAD

**Issue by ckotzbauer** [weaveworks/kured#140]
The official Helm-Chart of Kured is currently hosted on the "stable" repository of https://github.com/helm/charts.
When Helm 3 was released in last november, the maintainers also deprecated the "stable" and "incubator" repository.  So all charts have to move to own repos in a transition phase. See for more details: https://github.com/helm/charts#status-of-the-project

My suggestion is to move the chart to this repo and host it with github-pages. This is very simple and all sources are in one place for maintaining.

The following things have to be done for the migration:
* [x] Move the chart-sources to this repo.
* [x] Create CI-Jobs (e.g. Github Actions) to lint, test and release new chart versions
* [ ] ~~Maybe integrate into the release-process of kured itself.~~
* [x] Document the min-k8s version which is required in the Chart-Readme (should be 1.9 now)
* [x] List this chart-repo at Helm-Hub.
* [x] Deprecate the old chart at the stable-repo. (Add a link to its new home) https://github.com/helm/charts/blob/master/PROCESSES.md#deprecating-a-chart

ETA: Aug 13, 2020 (stable-repo will be de-listed from Helm-Hub then)

**Comment by dholbach** [comment]
Do we need to get the approval of the charts authors/contributors to be able to move the code? Any guidance from the Helm team on moving charts elsewhere?

**Comment by code-chris** [comment]
Technically we don't need their approval. We should add a deprecation notice to the readme and publish a last chart version with that info, that everybody is aware of the migration. Then it's up to each user when to switch their installation to the new chart-repository.
I'm not aware of any further guidenace for moving. But you can look at several charts in the stable-folder, which are already moved to other repos.

General notice for deprecations: https://github.com/helm/charts/blob/master/PROCESSES.md#deprecating-a-chart

**Comment by dholbach** [comment]
Added to [the agenda](https://docs.google.com/document/d/1bsHTjHhqaaZ7yJnXF6W8c89UB_yn-OoSZEmDnIP34n8/edit) of the next meeting (Wednesday May 27th, 16:00 UTC).

**Comment by dholbach** [comment]
Actions from the meeting:
- [ ] @dholbach and @ckotzbauer to review options of kured chart
- [ ] @dholbach to review practices of Flux team around helm chart releases

**Comment by ckotzbauer** [comment]
Quickly reconsidered the question, if integrating the charts in this repo or making a new repo under weaveworks-org. The GH-Actions create a GH-Release for each new chart version and that's not possible without creating a git-tag. This would lead to noise, as discussed in the meeting...

**Comment by dholbach** [comment]
It's what e.g. Flux does: https://github.com/fluxcd/flux/tags

**Comment by dholbach** [comment]
@ckotzbauer and I brief call and discussed this issue. Here are our notes: https://docs.google.com/document/d/1xDvASO9gyp_O6o0xw71CK0_0GpueijpcToozx4T-Yrs/edit#

Thanks a lot for the thorough review @ckotzbauer and your offer of help - much appreciated!

**Comment by dholbach** [comment]
Next steps as discussed in the call are:

- [ ] create initial PR which includes the [original chart](https://github.com/helm/charts/tree/master/stable/kured) in verbatim
- [ ] add all placeholders
- [ ] remove `autolock` feature, document how to upgrade
- [ ] file relevant issues for other TODO items
- [ ] @dholbach: create helm-chart issue label
- [ ] @dholbach: reach out to helm chart contributors to review PR (and potentially join the effort)
- [ ] set up chart release infrastructure (we'll likely use https://github.com/stefanprodan/helm-gh-pages)
- [ ] make a kured release
- [ ] release a chart, test
- [ ] follow process to deprecate original chart

**Comment by dholbach** [comment]
@ckotzbauer ^ LMK if I captured this right.

**Comment by ckotzbauer** [comment]
@dholbach Yes, you did!

**Comment by dholbach** [comment]
We're almost there. 

- [ ] Fix wrong indent in the new ServiceMonitor resource
- [ ] All cli-parameters are quoted now from the chart and it seems that kured cannot handle this in all cases. (time-zone, start-time, end-time, ...) have to be set without quotes
- [ ] Fill out README.md in gh-pages branch to be like e.g. https://github.com/fluxcd/charts/blob/gh-pages/index.md
- [ ] do another release
- [ ] test
- [ ] deprecate chart in /helm/charts/stable

**Comment by dholbach** [comment]
https://github.com/weaveworks/kured/pull/160
