### ISSUE TITLE
Passing flags during helm installation

### ISSUE THREAD

**Issue by lgmorand** [weaveworks/kured#142]
> arguments can be passed to kured via the daemonset pod template:

But is there a way to pass them at installation time ? I tried something like this without success.

`helm install kured stable/kured --namespace kured --set reboot-days="sa"`

**Comment by code-chris** [comment]
Hi @lgmorand,
all those parameters are cli-flags of kured itself. They can be set with the "extraArgs" object of the chart.

`helm install kured stable/kured --namespace kured --set extraArgs.reboot-days="Mon\,Tue"`

**Please note:** You have to escape special chars (e.g. `,`)

**Comment by lgmorand** [comment]
Thanks so much @code-chris !! I tried so many configurations for nothing. 

should definitly to be added in the readme

**Comment by dholbach** [comment]
> should definitly to be added in the readme

The README in https://github.com/helm/charts/tree/master/stable/kured - right?

**Comment by lgmorand** [comment]
![index](https://user-images.githubusercontent.com/6757079/81573673-15a14980-93a5-11ea-9c0f-b0d4df89c88b.jpg)

**Comment by dholbach** [comment]
@lgmorand I didn't mean to make you feel bad - I'm just asking as we're currently looking at #140

**Comment by lgmorand** [comment]
no worry ! <:o) I looked for the helm chart to "reverse engineering it" but didn't look at the right place. indeed, I looked for the helm chart within this repo, which seems logical

Anyway the docyou pointed is not clear enough for me, why don't they give a real exemple instead of foobar. But the example given by core-chris solved my issue

**Comment by dholbach** [comment]
That's useful feedback - thanks @lgmorand !
