### ISSUE TITLE
When using --annotationTTL, lock is not claimed by new owner

### ISSUE THREAD

**Issue by bboreham** [weaveworks/kured#143]
If `Acquire()` [returns on the `ttlExpired` path](http://github.com/weaveworks/kured/blob/ec755333941a4a647ac3d782c29016e89ea540c0/pkg/daemonsetlock/daemonsetlock.go#L48), it doesn't update the annotation.

It needs to go through [this line](http://github.com/weaveworks/kured/blob/ec755333941a4a647ac3d782c29016e89ea540c0/pkg/daemonsetlock/daemonsetlock.go#L64), otherwise the lock will still show as the previous owner, and all nodes will act as if they now own it.

**Comment by nkinkade** [comment]
Hello! Just checking on the status of this issue. I noticed this In the Kured 1.5.0 release notes:

> Adding --annotation-ttl for automatic unlock

We're currently using 1.4.4 and have found `--annotation-ttl` is not usable for us because of behavior that I imagine is a result of this bug.

Thanks!

**Comment by dholbach** [comment]
AFAIUI #213 solves this issue?
