### ISSUE TITLE
Cannot patch resource "daemonsets" in API group "apps"

### ISSUE THREAD

**Issue by stevegszabo** [weaveworks/kured#146]
Deployed kured helm chart using docker.io/weaveworks/kured:1.4.0

AKS v1.15.7: works - the job is able to lock/unlock the daemonset
AKS v1.16.7: Error from server (Forbidden): daemonsets.apps "infosec-kured" is forbidden: User "system:serviceaccount:infosec-kured:infosec-kured" cannot patch resource "daemonsets" in API group "apps" in the namespace "infosec-kured"

The role bound to the service account allows 'update' but not 'patch' for daemonsets.apps:

```
rules:
  # Allow kured to lock/unlock itself
  - apiGroups:     ["extensions"]
    resources:     ["daemonsets"]
    resourceNames: ["{{ template "kured.fullname" . }}"]
    verbs:         ["update", "patch"]

  - apiGroups:     ["apps"]
    resources:     ["daemonsets"]
    resourceNames: ["{{ template "kured.fullname" . }}"]
    verbs:         ["update"] <=== no patch

```
If we manually add 'patch' to the role for daemonsets.apps the jobs will work.

**Comment by ckotzbauer** [comment]
Hi,
we are currently migrating the chart to this repo. (see #140) It will be available in the next few days.
This bug was addressed during the migration, as several other changes.

**Comment by ckotzbauer** [comment]
@stevegszabo 
The new helm-chart is now available at https://github.com/weaveworks/kured/tree/master/charts/kured

**Comment by davidkarlsen** [comment]
This seems to have been fixed now: https://github.com/weaveworks/kured/blob/master/charts/kured/templates/role.yaml#L18 - so closing - feel free to reopen if needed.
