### ISSUE TITLE
kured is installed; however, testing "reboot" does not work

### ISSUE THREAD

**Issue by NMark02** [weaveworks/kured#148]
Hi
I have installed kured using helm, helm install -f kured-values.yaml kured stable/kured --namespace kured --set extraArgs.start-time=2am --set extraArgs.end-time=5am --set extraArgs.time-zone=Europe/Berlin --set extraArgs.reboot-days="sun\,sat"

AKS and node version: 1.16.9

**k get all -n kured**
NAME              READY   STATUS    RESTARTS   AGE
pod/kured-4tct2   1/1     Running   0          33m
pod/kured-zbx8n   1/1     Running   0          33m

NAME                   DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/kured   2         2         2       2            2           <none>          33m

**one of the PODS logs**
k logs kured-4tct2 -f -n kured
time="2020-06-14T19:44:36Z" level=info msg="Kubernetes Reboot Daemon: 1.4.0"
time="2020-06-14T19:44:36Z" level=info msg="Node ID: aks-agentpool-35064155-vmss000001"
time="2020-06-14T19:44:36Z" level=info msg="Lock Annotation: kured/kured:weave.works/kured-node-lock"
time="2020-06-14T19:44:36Z" level=info msg="Reboot Sentinel: /var/run/reboot-required every 1h0m0s"
time="2020-06-14T19:44:36Z" level=info msg="Blocking Pod Selectors: []"
time="2020-06-14T19:44:36Z" level=info msg="Reboot on: Sun---------------Sat between 02:00 and 05:00 Europe/Berlin"

I SSH to the AKS node and issued this command for testing, **sudo touch /var/run/reboot-required**
however; nothing happens, no reboot.
Could you please let me know what extra step I need to perform in order to complete my testing?
Thanks!

**Comment by NMark02** [comment]
Could someone please provide me with information? Thanks

**Comment by paprickar** [comment]
Hey @NMark02 

I am not using a reboot time range (Sun to Sat between 02:00 and 05:00) but you might just tested it at the wrong time?

I can see in the logs ```time="2020-06-14T19:44:36Z``` so there will be no reboot until 02:00 if I understood this correct.

**Comment by NMark02** [comment]
@paprickar thanks for taking the time and reply to my query. I will give it another try. Thanks so much!

**Comment by evrardjp** [comment]
Can we close this?

**Comment by NMark02** [comment]
yes please @evrardjp
