### ISSUE TITLE
Kured logs which indicate that node is rebooted

### ISSUE THREAD

**Issue by VarsChdhry** [weaveworks/kured#151]
I am new to kured and was just curious that which kured log exactly say that particular node is successfully rebooted.

Following are logs from kured:

`time="2020-06-21T03:00:09Z" level=info msg="Kubernetes Reboot Daemon: 1.3.0"
time="2020-06-21T03:00:09Z" level=info msg="Node ID: aks-node-188893-vmss1"
time="2020-06-21T03:00:09Z" level=info msg="Lock Annotation: kured/kured:weave.works/kured-node-lock"
time="2020-06-21T03:00:09Z" level=info msg="Reboot Sentinel: /var/run/reboot-required every 1h0m0s"
time="2020-06-21T03:00:09Z" level=info msg="Blocking Pod Selectors: []"
time="2020-06-21T03:00:09Z" level=info msg="Reboot on: Sun------------------ between 02:00 and 08:00 UTC"
time="2020-06-21T03:00:09Z" level=info msg="Holding lock"
time="2020-06-21T03:00:09Z" level=info msg="Uncordoning node aks-node-188893-vmss1"
time="2020-06-21T03:00:10Z" level=info msg="node/aks-node-188893-vmss1 uncordoned" cmd=/usr/bin/kubectl std=out
time="2020-06-21T03:00:10Z" level=info msg="Releasing lock"
time="2020-06-21T03:31:03Z" level=info msg="Reboot not required"`

Does these logs means kured has rebooted nodes, or there must be another logs such as msg="rebooted completed"?

 

Any suggestion would be greatly appreciated.

**Comment by evrardjp** [comment]
No reboot was done in that log.

If a reboot was triggered, you would have more details in your logs, like `Commanding reboot for node:`

**Comment by evrardjp** [comment]
Do you think we need more documentation?

**Comment by bboreham** [comment]
When I tested a reboot for #210 I did not get the "Commanding reboot" line fed through to my log store. 
I haven't investigated, but it does seem a bit chancy whether something will make it to disk in the context of a reboot.
Maybe kured should wait a short time between logging and rebooting to improve its chances?

**Comment by evrardjp** [comment]
That's weird, because the reboot command should try to sync all writes before effectively rebooting. I checked on my environment, and I indeed see the proper lines.
```
time="2020-10-29T12:47:32Z" level=info msg="Reboot not required"
time="2020-10-29T12:48:32Z" level=info msg="Reboot required"
time="2020-10-29T12:48:32Z" level=info msg="Acquired reboot lock"
time="2020-10-29T12:48:32Z" level=info msg="Draining node kind-control-plane2"
WARNING: ignoring DaemonSet-managed Pods: kube-system/kindnet-p45nd, kube-system/kube-proxy-shphl, kube-system/kured-tfj9d
time="2020-10-29T12:48:32Z" level=info msg="Commanding reboot for node: kind-control-plane2"
```

It's maybe a good idea to introduce a timer, but I don't think it's necessary.

**Comment by bboreham** [comment]
It might make it to disk, but when the container gets deleted on shutdown and the pod restarted after reboot I'm not enormously surprised one line can get lost.  Maybe I should have a better scheme to collect the logs (currently fluentd reading the files).

**Comment by evrardjp** [comment]
> It might make it to disk, but when the container gets deleted on shutdown and the pod restarted after reboot I'm not enormously surprised one line can get lost. 

Hehe,  me neither :)
