### ISSUE TITLE
Kured Pod is restarted frequently

### ISSUE THREAD

**Issue by MatthewZ627** [weaveworks/kured#153]
Issue: Kured Pod is restarted frequently

Here is result of running kubectl describe for Kured pod:

Name: kured-xhb62
Namespace: kured
Priority: 0
PriorityClassName: <none>
Node: aks-agentpool2-25811506-vmss000000/10.106.112.166
Start Time: Wed, 24 Jun 2020 17:34:49 +0800
Labels: app=kured
controller-revision-hash=5495dd5696
pod-template-generation=1
release=kured
Annotations: <none>
Status: Running
IP: 10.106.112.179
Controlled By: DaemonSet/kured
Containers:
kured:
Container ID: docker://c78b04996238e8503e8e1a62db522c87ac3a39489a4a2d1d804f71c8048b3fe1
Image: weaveworks/kured:1.4.0
Image ID: docker-pullable://weaveworks/kured@sha256:f7afa486e535a709fa88fa8053974b97718d0209dd23d9726f944f4b35cf8e0b
Port: 8080/TCP
Host Port: 0/TCP
Command:
/usr/bin/kured
Args:
--ds-name=kured
--ds-namespace=kured
State: Waiting
Reason: CrashLoopBackOff
Last State: Terminated
Reason: Error
Exit Code: 1
Started: Wed, 24 Jun 2020 19:52:42 +0800
Finished: Wed, 24 Jun 2020 19:53:12 +0800
Ready: False
Restart Count: 29
Environment:
KURED_NODE_ID: (v1:spec.nodeName)
Mounts:
/var/run/secrets/kubernetes.io/serviceaccount from kured-token-c5qfp (ro)
Conditions:
Type Status
Initialized True
Ready False
ContainersReady False
PodScheduled True
Volumes:
kured-token-c5qfp:
Type: Secret (a volume populated by a Secret)
SecretName: kured-token-c5qfp
Optional: false
QoS Class: BestEffort
Node-Selectors: beta.kubernetes.io/os=linux
Tolerations: node-role.kubernetes.io/master:NoSchedule
node.kubernetes.io/disk-pressure:NoSchedule
node.kubernetes.io/memory-pressure:NoSchedule
node.kubernetes.io/not-ready:NoExecute
node.kubernetes.io/pid-pressure:NoSchedule
node.kubernetes.io/unreachable:NoExecute
node.kubernetes.io/unschedulable:NoSchedule
Events:
Type Reason Age From Message
---- ------ ---- ---- -------
Warning BackOff 45s (x577 over 139m) kubelet, aks-agentpool2-25811506-vmss000000 Back-off restarting failed container

Error message for running kubectl logs:

time="2020-06-24T09:43:24Z" level=info msg="Kubernetes Reboot Daemon: 1.4.0"
time="2020-06-24T09:43:24Z" level=info msg="Node ID: aks-agentpool2-25811506-vmss000000"
time="2020-06-24T09:43:24Z" level=info msg="Lock Annotation: kured/kured:weave.works/kured-node-lock"
time="2020-06-24T09:43:24Z" level=info msg="Reboot Sentinel: /var/run/reboot-required every 1h0m0s"
time="2020-06-24T09:43:24Z" level=info msg="Blocking Pod Selectors: []"
time="2020-06-24T09:43:24Z" level=info msg="Reboot on: SunMonTueWedThuFriSat between 00:00 and 23:59 UTC"
time="2020-06-24T09:43:54Z" level=fatal msg="Error testing lock: Get https://192.168.128.1:443/apis/apps/v1/namespaces/kured/daemonsets/kured: dial tcp 192.168.128.1:443: i/o timeout"

Could anyone can help us? Thanks

**Comment by cloudoutloud** [comment]
Is this just happening on one node or all nodes in the cluster?
What is the status of node `aks-agentpool2-25811506-vmss000000`?

**Comment by MatthewZ627** [comment]
Status of node for aks-agentpool2-25811506-vmss_0 is health.

And only one node got this issue in Azure Kubernetes cluster, because just one node was created by AKS.

Thanks

**Comment by yongzhang** [comment]
The same issue, @MatthewZ627 can I ask what’s your kubernetes version and network CIDR (pod, service and VPC)? Thanks.

**Comment by evrardjp** [comment]
Are there policies preventing traffic?

**Comment by bboreham** [comment]
This error says the kured program is unable to talk to your Kubernetes api-server.  "i/o timeout" means nothing came back at all.
It suggests some misconfiguration in your Kubernetes, since nothing would run at all if the api-server was truly uncontactable.

**Comment by bboreham** [comment]
As it happens, I got one of these messages today, immediately after a reboot:
```
time="2020-10-29T10:30:46Z" level=fatal msg="Error testing lock: Get \"https://10.0.0.1:443/apis/apps/v1/namespaces/kube-system/daemonsets/kured\": dial tcp 10.0.0.1:443: i/o timeout"
```

I speculate that kube-proxy hasn't had time to set up the service address yet.
For me it was a one-off.

Related: #214
