### ISSUE TITLE
Cannot update and restart system if there are more than one AKS work nodes

### ISSUE THREAD

**Issue by Elven-coder** [weaveworks/kured#156]
There are 3 new AKS work nodes in my test case. The new work nodes were created at nearly same time. The issue I encountered is that Kured service only updated and restarted one of them. The two others cannot be updated and restarted automatically. 
period=5m
![image](https://user-images.githubusercontent.com/13388658/86028008-f600d600-ba63-11ea-936c-e614702d5f04.png)

**Comment by evrardjp** [comment]
Kured is doing a rolling restart. When your node is back up, the kured label should be removed, and the rest of the cluster can continue to restart if necessary.

Can you check the node's labels and annotations?
