### ISSUE TITLE
invalid period 

### ISSUE THREAD

**Issue by davidkarlsen** [weaveworks/kured#161]
If I install with the chart and have configuration.period=15m I get 
```
time="2020-06-30T14:35:48Z" level=fatal msg="invalid argument \"\\\"15m\\\"\" for \"--period\" flag: time: invalid duration \"15m\""
```
in the pods

**Comment by dholbach** [comment]
I believe this is

> All cli-parameters are quoted now from the chart and it seems that kured cannot handle this in all cases. (time-zone, start-time, end-time, ...) have to be set without quotes

from https://github.com/weaveworks/kured/issues/140#issuecomment-651737015

Right @ckotzbauer ?

**Comment by ckotzbauer** [comment]
Yes, this looks like this issue. :+1:
