### ISSUE TITLE
[Helm chart]: Support secret params

### ISSUE THREAD

**Issue by audunsolemdal** [weaveworks/kured#167]
My team uses flux with a public repo, and we deploy Kured as a helmrelease. https://github.com/equinor/sdp-flux/blob/prod/base/infrastructure/kured.yaml#L24

Currently there doesn't seem to be a way to set slackHookUrl from a Kubernetes secret. Slack automatically invalidates slack webhooks on public Github repos, making us unable to get slack alerts with our workflow.

**Comment by ckotzbauer** [comment]
Hm, that's a valid use-case I think.

The problem is, that all these settings are cli-arguments and helm is not able to inject a secret-value by itself on chart-rendering. So the only thing which might be possible is to set the slack-hook-url as environment variable of the kured daemonset, then the chart can be modified to reference an existing secret. But that's something which kured does not support, right now...

**Comment by davidkarlsen** [comment]
But it is possible to refer to a ${VARIABLE} in the args, and set the the value of the variable as a reference to a key in a secret.
@audunsolemdal note that using SOPS you can encrypt variables: https://github.com/fluxcd/flux/pull/2580
That can be a generic approach to handling secrets - and then these can be under version-control too.

**Comment by audunsolemdal** [comment]
> (...) and set the the value of the variable as a reference to a key in a secret.

Maybe I'm missing something, but I don't see how I can set an environment variable to the daemonset without modifying the helm chart.

@davidkarlsen 
My understanding is that you are suggesting using extraArgs to set an env variable to a secret?

But this doesn't use  the "env" field which is left unaltered by helm Chart config, making me unable to use e.g. valueFrom.secretKeyRef
https://github.com/weaveworks/kured/blob/master/charts/kured/templates/daemonset.yaml#L100

**Comment by davidkarlsen** [comment]
@audunsolemdal the first part of my comment was targeted at the chart maintainer, to inject the use of a var at https://github.com/weaveworks/kured/blob/master/charts/kured/templates/daemonset.yaml#L45 and secondly add the var in the env: section, referring to an secret and key within it.
