### ISSUE TITLE
"Failed to build time window: unknown time zone America/New_York" error when using timeZone flag

### ISSUE THREAD

**Issue by billimek** [weaveworks/kured#175]
Using the `kured` helm chart version 2.1.1 with the 1.4.5 kured release, with the `configuration.timeZone: "America/New_York"` setting ([see HelmRelease yaml](https://github.com/billimek/k8s-gitops/blob/master/kube-system/kured/kured.yaml#L24)), `kured` pods fail to start up crashing with the following error:

`"Failed to build time window: unknown time zone America/New_York"`

I also tried setting the value to `EST5EDT` and the same error occurs.

The golang time module documentation even shows `America/New_York` as an [example](https://golang.org/pkg/time/#LoadLocation) for a timezone to use.

**Comment by onedr0p** [comment]
I am having this issue too...

**Comment by davidkarlsen** [comment]
Related: https://github.com/weaveworks/kured/issues/120

**Comment by onedr0p** [comment]
This is still an issue

**Comment by dholbach** [comment]
Can somebody verify with the last version and point out their `kured` config here? I wonder if this is #206 in disguise.

**Comment by billimek** [comment]
Daniel, just tried with 1.5.1, and sadly no dice:

```
❯ k -n kube-system logs -f kured-9jzlt
time="2020-11-26T16:58:33Z" level=info msg="Kubernetes Reboot Daemon: unreleased"
time="2020-11-26T16:58:33Z" level=fatal msg="Failed to build time window: unknown time zone America/New_York"
```

Config is: https://github.com/billimek/k8s-gitops/blob/b64a3218a8dd74109b1977afc85e8ffbb0263c11/kube-system/kured/kured.yaml

**Comment by evrardjp** [comment]
@chentex Could you have a look at this? You have checked the code recently :)

**Comment by chentex** [comment]
Sure, I can take a look

**Comment by chentex** [comment]
I managed to track the error, it is in the image used `raspbernetes/kured` I have submitted a fix for them to make a new release.

**Comment by dholbach** [comment]
Wow, @chentex - great catch! Closing the issue here.
