### ISSUE TITLE
Should always drain before reboot

### ISSUE THREAD

**Issue by mxey** [weaveworks/kured#18]
According to https://github.com/weaveworks/kured/blob/d7b9c9fbec26e113d8b90499c3e58bc06098581c/cmd/kured/main.go#L256, kured will only drain the node before rebooting, if the node was not already cordoned/unschedulable.

Just because a node is marked unschedulable does not mean all workloads were already drained. The node might have been cordoned manually but not drained before, kured might have started a drain but might have been interrupted (crash, update, whatever) before finishing the drain. Always running drain before reboot makes this safer, and if there are no more workloads to drain, is effectively a no-op.

**Comment by damoon** [comment]
why was skipping the drain implemented in the first place?
does someone remember or this there some documentation?
