### ISSUE TITLE
migrate kured from helm2 to helm3

### ISSUE THREAD

**Issue by dawn-chu** [weaveworks/kured#182]
Hi, we have kured installed in our AKS cluster with helm2 from stable/kured(https://github.com/helm/charts/tree/master/stable/kured).
We are trying to migrate this chart to use helm3. Seems now the repo has been changed to https://weaveworks.github.io/kured. Can I use the [helm2to3](https://github.com/helm/helm-2to3) plugin to migrate this chart or I need to remove this chart which is installed by helm2 and then reinstall with helm3 by 
`helm repo add kured https://weaveworks.github.io/kured 
helm install my-release kured/kured`

**Comment by ckotzbauer** [comment]
Generally, you should be able to migrate the chart with this utility to helm3. But this does only migrate the release-information to the new storage format helm3 uses. (I didn't test it for kured)
In the second step you can upgrade the chart to use the new repository. This should work without a clean reinstall. However this shouldn't be a problem, since kured does not store and persistent data.

**Comment by dawn-chu** [comment]
Sounds like there are two steps:
1.use helm2to3 plugin to migrate this chart to helm3 
2.do "helm upgrade" on this chart to update this chart to use new repository

**Comment by ckotzbauer** [comment]
exactly!

**Comment by dholbach** [comment]
Shall we document this somewhere in our docs?

**Comment by ckotzbauer** [comment]
We can document, that the migration to the new chart is only a simple "helm upgrade" command with the new repo and parameters....
I wouldn't document the helm2to3 thing, since this is not related to kured and is generally useable for any helm-chart.

**Comment by davidkarlsen** [comment]
You can use the guide https://helm.sh/blog/migrate-from-helm-v2-to-helm-v3/ to migrate. It has some trickiness depending on how charts have been designed (I had some conflicting labels).
On the other side the kured chart is stateless (no ingresses to be reached, no volumes, no services exposed which will break anything) - so the easiest could be a simple reinstall.
