### ISSUE TITLE
taint node with PreferNoSchedule until it gets drained

### ISSUE THREAD

**Issue by damoon** [weaveworks/kured#19]
In case of multiple nodes asking to restart, pods will be moved more often then needed, because they can start on the node that will be rebooted next.
The use of PreferNoSchedule on nodes waiting to be rebooted, will prefer scheduling pods onto already rebooted nodes.

link: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/

**Comment by damoon** [comment]
@weaveworksbot i am still interested in this

**Comment by bboreham** [comment]
Isn't there a danger that every node is waiting to reboot (e.g. if Ubuntu push out a security patch), so this would mean no pods can get scheduled?

**Comment by damoon** [comment]
The taint is PreferNoSchedule not NoSchedule.
The scheduler will try to avoid putting pods on these nodes, but do it if no other placement is possible.
