### ISSUE TITLE
More then one reboot a time

### ISSUE THREAD

**Issue by limberger** [weaveworks/kured#193]
What do you think  about implement more then one reboot a time (a number informed by parameter)?
In one big clusters maybe could be a cool and useful implementation. I can try to create a Pull Reques whith this implementetion  if do you agree!!!

**Comment by evrardjp** [comment]
Oh that's an interesting concept!

How would you recognize which node deserve reboot or not?
Would you use the same concept as today to "disable" reboots for some nodes, and then update? I have the impression this kind of logic better suits a controller of kured daemonsets :)

**Comment by limberger** [comment]
Hi! Using the same logic of semaphores ... just thinking to create a parameter (--CONCURRENT-REBOOTS) and a set of 'lock-annotation' with this count of 'locks' ... 
The lock anotation maybe could be: weave.works/kured-node-lock-###-@@@@@@@@
where ### => lock sequential and @@@@@@@@ => NodeName.
I think with this is possible to control more then one reboot a time!

**Comment by evrardjp** [comment]
Yes! We've already discussed of implementing another kind of locking location, so that might be an adjacent work.
By any chance, do you have the time to tackle this kind of work? @dholbach what do you think of the feature?
