### ISSUE TITLE
Helm install with set parameters is not applied

### ISSUE THREAD

**Issue by RoyKimYYZ** [weaveworks/kured#200]
I have an Azure Kubernetes Service cluster. 

helm install kured kured/kured --namespace kured --set nodeSelector."beta\.kubernetes\.io/os"=linux  `
    --set configuration.start-time=0:00 `
    --set configuration.end-time=3:59:59 `
    --set configuration.timeZone=America/New_York `
    --set service.create=true `
    --set service.port=8081 `
    --set configuration.rebootDays[0]="sun" `
    --set configuration.rebootDays[1]="tue"

When I exec into a pod and run Kured, I only see default settings and not the expected settings passed into the helm install.

OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"bash\": executable file not found in $PATH": unknown
/ # kured
INFO[0000] Kubernetes Reboot Daemon: 1.5.0              
INFO[0000] Node ID: aks-system1184-83018174-vmss000002  
INFO[0000] Lock Annotation: kube-system/kured:weave.works/kured-node-lock 
INFO[0000] Reboot Sentinel: /var/run/reboot-required every 1h0m0s 
INFO[0000] Blocking Pod Selectors: []                   
INFO[0000] Reboot on: SunMonTueWedThuFriSat between 00:00 and 23:59 UTC 
INFO[0000] Force annotation cleanup disabled.           
FATA[0000] listen tcp :8080: bind: address already in use 
/ # 

![image](https://user-images.githubusercontent.com/1959074/93219535-79fc5d00-f739-11ea-8d93-3786c5930b52.png)

**Comment by evrardjp** [comment]
@ckotzbauer Did you already see this kind of things in the past?

**Comment by ckotzbauer** [comment]
I will investigate this issue in the evening, if I have time.

**Comment by ckotzbauer** [comment]
So, only to understand things right @RoyKimYYZ:
- You install the helm-chart (the pods are starting)
- You connect with `kubectl exec` into the pod
- Execute `kured` binary?

This indeed would start kured with its default settings, as there are no cli-parameters given.
Can you post the logs of the pod (`kubectl logs <kured-pod>`) without doing a exec before?

**Comment by evrardjp** [comment]
@ckotzbauer oh yes, good catch! :) I didn't realise kured was just run with the no parameters during the executing inside the pod, and thought those logs were the kubectl logs ... My bad!

**Comment by ckotzbauer** [comment]
No problem @evrardjp 😆 :+1:

**Comment by RoyKimYYZ** [comment]
@ckotzbauer Ok I understand now. Then how does one validate the setup is what is intended via helm chart install with the params?

**Comment by ckotzbauer** [comment]
You can view the logs with `kubectl logs` to ensure kured is configured correctly.
