### ISSUE TITLE
Kured pods is not deployed to all nodes in 2 node pools AKS

### ISSUE THREAD

**Issue by RoyKimYYZ** [weaveworks/kured#201]
I have an Azure Kubernetes cluster. 1 system node pool of 2-3 nodes and 1 user node pool of 2 nodes. 

When installing Kured  with helm 
helm install kured kured/kured --namespace kured --set nodeSelector."beta\.kubernetes\.io/os"=linux

The kured daemonset only has pods to the system node pool. The user node pool does indeed have the label beta.kubernetes.io/os: linux yet still does not have pods in these nodes.

Is this a bug or do I have to install another Kured daemonset specifically targeting the 2nd node pool? If so, please provide guidance.

**Comment by cloudoutloud** [comment]
If you deploy out with no node selector flag. Kured deamonset should deploy one pod to all nodes I believe.

Do you have taints on the user node pool nodes, preventing scheduling of new pods?

**Comment by RoyKimYYZ** [comment]
Yes I recall I have a taint. I will check that out.

Roy Kim
Azure & Office 365 Consultant

www.roykim.ca<http://www.roykim.ca/> |@RoyKimYYZ | Github<https://github.com/roykimyyz>
[cid:image003.png@01D68C47.B5574390]

**Comment by RoyKimYYZ** [comment]
I resolved my issue by adding the paramaters into my helm command
--set tolerations[0].effect=NoSchedule `
    --set tolerations[0].key=node-role.kubernetes.io/agent `
    --set tolerations[1].operator=Exists `
    --set tolerations[1].key=CriticalAddonsOnly `
    --set tolerations[2].operator=Exists `
    --set tolerations[2].effect=NoExecute `
    --set tolerations[3].operator=Exists `
    --set tolerations[3].effect=NoSchedule

This is in Azure Kubernetes cluster. 

Thanks for the help.
