### ISSUE TITLE
StartTime EndTime Flags don't wrap around - can block reboots

### ISSUE THREAD

**Issue by slynickel** [weaveworks/kured#204]
### Problem
If the startTime command flag is set to be after endTime kured can never reboot. timewindow.Contains() always returns false.

#### Potential Unit Test Showing the Problem 
You can add the following test case to `pkg/timewindow/timewindow_test.go` 
```go
	tests := []struct {
		days  string
		start string
		end   string
		loc   string
		cases []testcase
	}{
....
		{"mon,tue,wed,thu,fri", "9pm", "5am", "America/Los_Angeles", []testcase{
			{"2019/04/04 00:49 PDT", true}, // Would expect 12:49am to be between 9pm and 5am
			{"2019/04/04 22:49 PDT", true}, // Would expect 10:49pm to be between 9pm and 5am
			{"2019/04/05 08:59 PDT", false},
			{"2019/04/05 9:01 PDT", false},
			{"2019/03/31 10:00 PDT", false},
			{"2019/04/04 12:00 PDT", false},
		}},
```
And it will fail.

```bash
$ go test -timeout 30s github.com/weaveworks/kured/pkg/timewindow -run ^TestTimeWindows
--- FAIL: TestTimeWindows (0.00s)
    timewindow_test.go:64: (---MonTueWedThuFri--- between 21:00 and 05:00 America/Los_Angeles) contains (2019/04/04 00:49 PDT) didn't match expected result of true
    timewindow_test.go:64: (---MonTueWedThuFri--- between 21:00 and 05:00 America/Los_Angeles) contains (2019/04/04 22:49 PDT) didn't match expected result of true
FAIL
FAIL    github.com/weaveworks/kured/pkg/timewindow      0.006s
FAIL
```
If kured is setup this way nothing happens other timewindow.Contains() returns false for all times.

### Impact
A user of kured can improperly configure kured in way that will result in kured never rebooting for no obvious reason. Nothing is printed to the log. The startup of kured looks reasonable. (The following is for a slightly different configuration).

```bash
$ kubectl logs -n kube-system kured-hsgrx
time="2020-09-14T20:05:21Z" level=info msg="Kubernetes Reboot Daemon: 1.4.5"
time="2020-09-14T20:05:21Z" level=info msg="Node ID: <REDACTED>"
time="2020-09-14T20:05:21Z" level=info msg="Lock Annotation: kube-system/kured:weave.works/kured-node-lock"
time="2020-09-14T20:05:21Z" level=info msg="Reboot Sentinel: /var/run/reboot-required every 1h0m0s"
time="2020-09-14T20:05:21Z" level=info msg="Blocking Pod Selectors: []"
time="2020-09-14T20:05:21Z" level=info msg="Reboot on: SunMonTueWedThuFriSat between 21:00 and 05:00 America/Chicago"
time="2020-09-14T20:05:21Z" level=info msg="Force annotation cleanup after: 2h0m0s"
```

### Suggested Fix
A simple stop gap would be to include in the readme and other examples a warning that the startTime flag MUST be before the endTime flag. Wrap around is not possible.

Code fixes could include:
- Don't allow kured to start if startTime is after end time with a meaningful error message.
- Support time wrap around in timewindow.Contains.

**Comment by theharleyquin** [comment]
Please confirm if an actual issue. Have similar setup where i want the reboot window to be from 2300 - 0600:
            - --end-time=06:00
            - --start-time=23:00
            - --time-zone=America/New_York

**Comment by evrardjp** [comment]
Very good issue!

I don't have time to tackle this right now, but I think it's a simple fix.

**Comment by chentex** [comment]
I would like to tackle this, if it is OK.

**Comment by evrardjp** [comment]
Please go ahead @chentex ! :)
