### ISSUE TITLE
Error handling via log.Fatal() hurts operability

### ISSUE THREAD

**Issue by bboreham** [weaveworks/kured#214]
If run as expected in a pod, calling `log.Fatal()` means Kubernetes will restart the pod immediately and the operator will have to hunt down the error message in the previous logfile.

For instance: https://github.com/weaveworks/kured/blob/72c4112e2064bec2096ab450c3fb13876d7f3b68/cmd/kured/main.go#L207
https://github.com/weaveworks/kured/blob/72c4112e2064bec2096ab450c3fb13876d7f3b68/cmd/kured/main.go#L219
https://github.com/weaveworks/kured/blob/72c4112e2064bec2096ab450c3fb13876d7f3b68/cmd/kured/main.go#L233

**Comment by evrardjp** [comment]
Agreed.

**Comment by evrardjp** [comment]
However, where should we bubble up the error, if we don't panic/Fatal? Should kured continue even if it can get hold of locks? That sounds a recipe for disaster too. I guess we can just Errorf, and maybe abruptly quit rebootAsRequired ?

**Comment by bboreham** [comment]
Yes, it needs thought regarding retries, rate-limiting, etc.  This is something that we get from CrashLookBackoff in the current implementation.

Could have a metric for errors and a suggestion to alert if too many?

**Comment by evrardjp** [comment]
TBH What I like the most about kured is its simplicity. I would resist adding more complexity to it. This will indeed be non-trivial if we don't rely on kubernetes anymore.
