### ISSUE TITLE
Adding a chart to kubernetes/charts

### ISSUE THREAD

**Issue by plumdog** [weaveworks/kured#22]
Hi,

I've just opened a PR - https://github.com/kubernetes/charts/pull/6470 - to add a helm chart for kured, with a view to making kured easy to helm-install.

I thought it'd be sensible for me to create an issue here for two reasons:
1) to just sort of check that the creator(s) of kured are fine with that
2) to see if anyone who understands kured better than me wanted to look at the chart and either suggest changes (if the PR hasn't merged at time of reading) or contribute their own changes (if it has).

**Comment by vanto** [comment]
The referenced helm PR has been merged, this ticket can be closed.
