### ISSUE TITLE
blocking-pod-selector blocks on non-running pods

### ISSUE THREAD

**Issue by roy-work** [weaveworks/kured#227]
`kured`'s `--blocking-pod-selector` appears to only look for the existence of `Pod`s matching the given selector. This means that pods in, e.g., the state `Completed` (such as a finished `CronJob`) will block reboots; I don't believe this is how this feature is intended to work.

We run `kured` in a Kubernetes cluster, and we have a few `CronJob`s that we run that we want to block reboots. Thus, we configured `kured` with `--blocking-pod-selector=kured-prevent-reboot=true`; we then set that label on the relevant `CronJob`s. We are seeing `kured` refuse to reboot nodes, even when those jobs aren't running.

The code I think is involved in this process is [here](https://github.com/weaveworks/kured/blob/64202ff440ae51e5fe3eafb0c614426f638bc53f/cmd/kured/main.go#L174-L196), and appears pretty straight-forward: it merely lists out pods according to the provided label, and adds a field selector to restrict to only pods scheduled on the same VM as the `kured` that is doing the query. I think the only thing it misses is that it isn't ignoring pods in the `Completed` or `Error` states; they _exist_, but they're not really running, and preventing reboots means a `CronJob` that — even though it doesn't overlap `kured`'s window — keeps getting scheduled on the same node can prevent reboots indefinitely by just having the `Completed` pod hanging around.

---

As an example, In our logs, we see:

```
time="2020-11-08T00:59:52Z" level=warning msg="Reboot blocked: matching pods: [AAA-1604739600-v876j BBB-1604732400-pr2ps CCC-1602165600-fptr4 CCC-1602165600-j8m4f DDD-1604296800-qx5pb]"
```
(I've masked the names of the jobs.)

As an example, the `-v876j` `Pod` is first created:
```
"I1107 09:00:08.288281    2228 kubelet.go:1901] SyncLoop (ADD, \"api\"): \"AAA-1604739600-v876j_eee(<snip>)\""
```
About 10 minute later, it finishes:
```
"I1107 09:11:01.820871    2228 kubelet.go:1946] SyncLoop (PLEG): \"AAA-1604739600-v876j_eee(<snip>)\", event: &pleg.PodLifecycleEvent{ID:\"<snip>\", Type:\"ContainerDied\", Data:\"<snip>\"}"
```
Then, _much_ later, we get the above message from `kured`:
```
time="2020-11-08T00:59:52Z" level=warning msg="Reboot blocked: matching pods: [AAA-1604739600-v876j BBB-1604732400-pr2ps CCC-1602165600-fptr4 CCC-1602165600-j8m4f DDD-1604296800-qx5pb]"
```
(`kured` continues to try, but keeps failing, eventually reaching the end of its window.)

Then, later, k8s actually deletes the pod:
```
"I1108 09:14:13.307793    2228 kubelet.go:1917] SyncLoop (DELETE, \"api\"): \"AAA-1604739600-v876j_eee(<snip>)\""
```

This implies to me that the pod was `Completed` well before `kured`'s window.

**Comment by chentex** [comment]
I will take this.

**Comment by evrardjp** [comment]
Thanks @chentex ! There are a few PRs touching this code, so let's see what your analysis returns and synchronise with those PR to avoid conflicts :)

**Comment by georgekaz** [comment]
Has this been fixed or just closed? It doesn't look like it's been fixed.
