### ISSUE TITLE
Request: images for other architectures

### ISSUE THREAD

**Issue by anguslees** [weaveworks/kured#23]
Feature request: Please provide images for other architectures (more than amd64) as part of your release.

kured needs to run on every node, and for my cluster that means amd64, arm, and arm64.  I can build those myself, but it would be better if other similar users could also benefit from some centralised effort to support other archs.  Thanks :)

**Comment by anguslees** [comment]
If it helps, I have some cross-building (arm) Dockerfiles in https://github.com/anguslees/kured-docker - autobuilt images are at quay.io/anguslees/kured-{amd64,arm}.

Note the Dockerfiles are based on alpine, including a dbus-send replacement for `systemctl reboot`

**Comment by jmreicha** [comment]
@anguslees I just opened https://github.com/weaveworks/kured/pull/56 if you're interested.

**Comment by paulfantom** [comment]
Since #56 was closed I implemented a simple GH workflow for building multi-arch images in https://github.com/paulfantom/dockerfiles/blob/master/.github/workflows/kured.yml with images available at [quay.io/paulfantom/kured](https://quay.io/repository/paulfantom/kured?tab=tags). Maybe someone will find it useful to implement a similar workflow in this repository.

Sorry for pinging on the closed issue.

**Comment by evrardjp** [comment]
Don't be sorry! It proves interest.

Do you think you could provide a PR to update our workflows with this kind of content?

**Comment by paulfantom** [comment]
Right now I don't have the capacity to tackle this.

**Comment by anthr76** [comment]
Should this be re-opened?

**Comment by anthr76** [comment]
Are PRs welcome?

**Comment by dholbach** [comment]
yes, very much so - Jonathan McCracken wanted to take a look at this as well, if memory serves...

**Comment by evrardjp** [comment]
Yes, any help is welcomed.

**Comment by kingdonb** [comment]
I am using the kured image from `quay.io/paulfantom/kured` @ 1.7.0 and it works great, my cluster is a multiarch with Raspberry Pi CM3+ running as `arm` architecture (32 bit), and an amd64 machine. @anthr76 If you want to take a stab at the PR, I would be happy to review it here. (If you don't get around to it, I will come back and figure it out myself eventually.)

Here is the `kustomization.yaml` that I used to install on my cluster:

https://bitbucket.org/kingdonb/csh-flux/src/main/infrastructure/kured/kustomization.yaml

**Comment by davideshay** [comment]
@dholbach  , @evrardjp ,  I have added pull request #496  that should handle this. It supports amd64 and arm64 -- i didn't have any straight arm hardware to test, but it should work just by adding "arm" to the platforms list.
