### ISSUE TITLE
Helm Chart Alert Filter Quoted

### ISSUE THREAD

**Issue by jscannell** [weaveworks/kured#233]
The helm chart applies the quote function to the alertFilterRegexp variable. This causes the filter to be passed to kured exactly as "^(RebootRequired)$" and as a result filters are not functioning. As a workaround, using extraArgs.alert-filter-regexp to bypass the quote function allows filters to work as expected. The quote function should be removed from the chart.

**Comment by ckotzbauer** [comment]
Hi @jscannell,
this was fixed with #166 (Chart-Version 2.2.1). Which version of the chart you are using?

**Comment by jscannell** [comment]
The chart version is 2.2.0.

**Comment by jscannell** [comment]
Has version 2.2.1 been published to the helm repo? The latest version I see after repo update is 2.2.0.

**Comment by ckotzbauer** [comment]
Oh, you are right. It is not released yet. @dholbach Is there a patch release planned in the next weeks?

**Comment by dholbach** [comment]
@ckotzbauer We can certainly roll one.

**Comment by dholbach** [comment]
I think this can be closed now. Please let us know if it's still broken.

https://github.com/weaveworks/kured/releases/tag/1.5.1
