### ISSUE TITLE
Implement lifecycle hook/grace timeout functional test

### ISSUE THREAD

**Issue by evrardjp** [weaveworks/kured#239]
We already have a PR to test cluster features of kured https://github.com/weaveworks/kured/pull/183.

We should take this PR as inspiration to include a CI test (if possible in github actions) that does the following:
- spin up a small kind cluster (2 nodes would be enough, check existing PR and modify if necessary)
- deploy kured and a pod whose manifest contains a lifecyle preStop hook logging something (needs new manifest)
- write the reboot sentinel on the worker node (check existing PR)
- check that the pod with preStop hook behaved properly (simple code to be written)
- check that kured restarts the node successfully (check existing PR)

**Comment by atighineanu** [comment]
I can tackle this Issue. 
If everyone agrees, I would kindly prefer to go the upstream ginkgo way.

**Comment by evrardjp** [comment]
How would that work?
