### ISSUE TITLE
Test again k8s 1.{18,19,20}.x

### ISSUE THREAD

**Issue by dholbach** [weaveworks/kured#267]
In prep for the 1.6.0 release, we should test against the latest 3 releases now that k8s 1.20.0 is out.

**Comment by evrardjp** [comment]
I will tacke the update of the gh actions.

**Comment by evrardjp** [comment]
The CI will only test so much, so I suppose we need manual testing of prometheus/slack before closing this issue.

**Comment by dholbach** [comment]
:heavy_check_mark: Smoketest against local minikube 1.20.1, 1.19.6, 1.18.14 with 86fe6ff (no prometheus, slack testing).

**Comment by dholbach** [comment]
Looks like things are working all right in our Dev cluster too, Slack notifications turned up fine as well.

**Comment by dholbach** [comment]
Suggested release notes:
-------------------------------------

From a user perspective, this release will mostly bring you up to date with Kubernetes 1.[18,19,20].x. Behind the scenes Jean-Philippe Evrard (SuSE) put a lot of effort into automated testing, which will give us more confidence in the code we merge.

# Improvements
- add additional parameters to override the drain/reboot slack messages
- rename message template parameters so they are not related to slack
- Improve coordinated reboot output
- Add more logs into gates
- Added support for time wrap in timewindow.Contains


# Build / testing

- Bump to golang 1.15
- Add smoke/basic functional test
- Auto expire issues and PRs
- Always have latest helm binary installed
- Increase kubernetes versions test matrix for smoke tests
- Add kustomize testing
- Simplify manifest testing
- Add Shellcheck
- Cleanup github actions
- Fix chart linter
- Simplify action code
- Do not bump kubernetes with dependabot
- Force golang version
- Publish image on tag
- Point docs to current golang version
- Publish image on master merged changes
- Update for kubernetes 1.20 support
- Fix comment spacing
- Auto-publish helm chart on master change
- Do not bump any k8s module
- Temporarily workaround alpine issue

# Docs
- Clarify development process
- Clarify development process for helm charts
- Corrected README Setting a schedule configuration example

# Kubernetes Version Compatibility

The daemon image contains a 1.18.x k8s.io/{client-go,kubectl} for the purposes of maintaining the lock and draining worker nodes. Kubernetes aims to provide forwards & backwards compatibility of one minor version between client and server, so -this should work on 1.1{18,19,20}.x.

Thanks a lot to everyone who contributed to kured since 1.5.1. Commits from @DaniJG, dependabot[bot], @dholbach, @evrardjp, @jack-education, @morancj.
