### ISSUE TITLE
`--message-template` options not recognized by 1.5.1

### ISSUE THREAD

**Issue by nerijusk** [weaveworks/kured#271]
Using the `--message-template-drain` produces error:
```
Error: unknown flag: --message-template-drain
```

Even though the README documents it at https://github.com/weaveworks/kured#slack-notifications

**Comment by evrardjp** [comment]
Does the README show it for the tag you're running?

I am worried you might be trying a feature that's not yet released.

**Comment by evrardjp** [comment]
I don't see message-template-drain in our latest release: https://github.com/weaveworks/kured/blob/1.5.1/README.md

**Comment by nerijusk** [comment]
I followed https://github.com/weaveworks/kured/. Wrong assumption on my side then.

**Comment by evrardjp** [comment]
@nerijusk I think it's fair to say that it's confusing. It would be good to only expose the options when a released version of kured is out, but it means more work when doing the release (tag, test, publish documentation, change helm chart, publish helm chart). I think it's fair to include documentation when a feature lands in the code branch. WDYT?
