### ISSUE TITLE
Testing lock failed frequently due to API server unavailability 

### ISSUE THREAD

**Issue by atiasadir** [weaveworks/kured#272]
We are using Kured (currently version 1.4.4) on AKS-Engine cluster, K8s version 1.16.15.
The kured daemon-set restarts dozen of times and pod deletion / rollout restart doesn't help.
Looks like there are transient and frequent issues with API server availability, which causes TLS handshake timeouts.

we always get the same error message:
`msg="Error testing lock: Get https://10.0.0.1:443/apis/apps/v1/namespaces/kube-system/daemonsets/kured: net/http: TLS handshake timeout"`

It will be great to add some retries to requests related to API server.
And reduce the readiness/liveness sensitivity

similar issue #115 , opened new one since it's closed.

**Comment by 616b2f** [comment]
We have a similar issue:

`Error testing lock: Get https://somedomain:443/apis/apps/v1/namespaces/kube-system/daemonsets/kured: dial tcp: i/o timeout`

Killing the pod resolves the issue. Some retry logic would be awesome.
