### ISSUE TITLE
Using slack Incoming webhooks and Channel give a 404

### ISSUE THREAD

**Issue by knutia** [weaveworks/kured#299]
When using both parameters: 
--slack-hook-url string               slack hook URL for reboot notifications
and
--slack-channel string                slack channel for reboot notifications
ex:

> --slack-hook-url=https://hooks.slack.com/services/Txxxxxxxx/Bxxxxxxxxxx/xxxxxxxxxxxxxxx
> --slack-channel=notifications

the notification fails to send message to slack and the log contains the following message:

> level=warning msg="Error notifying slack: 404 Not Found" 

It looks like the slack Incoming webhooks URL dos does not support payload containing the "channel:" whit a value. by not setting the parameter "slack-channel" the notification to the slack Incoming webhooks URL works.

Looking at slack documentation at https://api.slack.com/messaging/sending#sending_methods. it states on the Incoming webhooks:
> A uniquely generated URL that is tied to a specific conversation.

This is also followed up by the fact you chouse your channel when you [create the slack Incoming webhook](https://api.slack.com/messaging/webhooks#create_a_webhook).

My suggestion for a solution is:

1.  To update the documentation to mention not to use "--slack-channel" when using slack Incoming webhook URL
2. To remove or rename the parameter --slack-channel.

The first option leave the option to use "--slack-hook-url" to point to an URL for "self-made" notifications service that can handle payload containing the channel.

**Comment by evrardjp** [comment]
@knutia Did you see the current work of @atighineanu ? It's moving towards the use of a single url, using shoutrrr (and its format).

With that in mind, do you think we should spend time fixing the slack-channel?

**Comment by evrardjp** [comment]
I am closing this, as we have an alternative. Feel free to re-open if necessary.
