### ISSUE TITLE
Expose changes of #315 in Helm chart

### ISSUE THREAD

**Issue by dholbach** [weaveworks/kured#332]
Have a look at #315 and expose changes in Helm chart please.

**Comment by atighineanu** [comment]
I am on it.

**Comment by atighineanu** [comment]
Here is the PR:
https://github.com/weaveworks/kured/pull/333

**Comment by evrardjp** [comment]
That will probably have to be _post_ 1.7.0. Do we need to update the manifest building for 1.7.0, though, to expose this feature?

**Comment by ckotzbauer** [comment]
#338 is merged
