### ISSUE TITLE
Update k8s test matrix to include 1.{19,20,21}

### ISSUE THREAD

**Issue by dholbach** [weaveworks/kured#347]
According to https://github.com/weaveworks/kured/#kubernetes--os-compatibility `main` should be compatible to 1.19.x, 1.20.x, 1.21.x, but that's not what we're currently testing in CI.

**Comment by evrardjp** [comment]
Good catch!!!

**Comment by evrardjp** [comment]
Kind node for 1.21 is not yet published on dockerhub [1]. Either we wait for it, we help update upstream, or we move towards building our own. As kind contributors have been historically good at maintaining those containers, I suggest we wait to update to kind 1.21. It shouldn't prevent us from readying our branch for 1.21 though.

[1]: https://hub.docker.com/r/kindest/node/tags?page=1&ordering=last_updated

**Comment by dholbach** [comment]
Perfect - that makes sense!

**Comment by evrardjp** [comment]
- `kind-cluster-1.21.yaml` will have to be created in https://github.com/weaveworks/kured/tree/main/.github  when the kindest node v1.21.0 is out.
- we need to then add the 1.21 to the matrix in the github workflows.

**Comment by evrardjp** [comment]
See also https://github.com/kubernetes-sigs/kind/issues/2188

**Comment by dholbach** [comment]
→ https://github.com/weaveworks/kured/pull/349
