### ISSUE TITLE
Adjust kured to use the new Microsoft Teams connector webhook URL format

### ISSUE THREAD

**Issue by papanito** [weaveworks/kured#362]
As mentioned in [#138 of shoutrrr](https://github.com/containrrr/shoutrrr/issues/138) the Microsoft Teams connector webhook URL format changed. Before it was `https://outlook.office.com/webhook/{tokenA}/IncomingWebhook/{tokenB}/{tokenC}` wheras of today, the base url is `https://<tName>/....`

Thus one should be able to also specify the `<tName>` i.e. something like this: `teams: teams://tName/token-a/token-b/token-c`

The new url is already reflected in v0.4.0 of `shoutrrr`

**Comment by evrardjp** [comment]
What's the problem? I have the impression that our code should be okay. Do we have an issue? We are using shoutrrr 0.4.3.

**Comment by papanito** [comment]
Not sure as the [documentation](https://github.com/weaveworks/kured#notifications) states
```
teams: teams://token-a/token-b/token-c
```
I did not look at the code but if you say I actually can pass `--notify-url=teams://tName/token-a/token-b/token-c`, then no there is probably no issue.
