### ISSUE TITLE
Add ability to set cli flags with environment variables

### ISSUE THREAD

**Issue by dkulchinsky** [weaveworks/kured#383]
Hey folks 👋🏼 

Would be great if we could define the CLI flags also with Environment Variables, this is especially important for arguments that are somewhat sensitive (like `--notify-url`) where we mutate the value from Vault.

Thanks!

**Comment by evrardjp** [comment]
That sounds a great idea!

**Comment by anderius** [comment]
Is there a workaround for this? I see no way to specify notifyUrl from a secret (using the Helm chart), and not using a secret is not an option.

**Comment by ckotzbauer** [comment]
This is currently not possible. The problem is not the helm-chart I think (it supports extraEnvVars which can be populated from secrets), but the code from kured itself. Currently kured does not read flags from the command line. But this should be easily possible to implement in `main.go` with the existing viper-library.

**Comment by dkulchinsky** [comment]
Thanks @ckotzbauer!

I was looking into this earlier today and came across this issue: https://github.com/spf13/viper/issues/671

and it looks like integrating viper & cobra for what's needed here comes with a pretty big caveat.

but not all seem lost: https://github.com/spf13/viper/issues/671#issuecomment-671067523 suggests that this is indeed possible but requires some glue code to make it work right.

**Comment by ckotzbauer** [comment]
Thanks for your research.
Yes, it is possible with a bit of code, but that should not be a blocker 😉 
Would you mind opening a PR for that?

**Comment by dkulchinsky** [comment]
Hey @ckotzbauer, my attempt to crack this in https://github.com/weaveworks/kured/pull/464

This seem to plumb nicely into the existing code and works as expected.

comments/suggestions are welcome 😄

**Comment by ckotzbauer** [comment]
I'll have a look today, thanks!! 🎉
