### ISSUE TITLE
Disable kured for a couple weeks

### ISSUE THREAD

**Issue by Scorito-Dev** [weaveworks/kured#387]
Hi,

Due to our priorities we want to disable kured for a couple weeks to make sure we are not running into issues.
Currently our configuration is as follows;
`configuration:
  endTime: "03:00"
  rebootDays: ["tue"]
  startTime: "02:00"
  timeZone: "UTC"`
  
  Is it possible to disable the reboot? what would happen if I do not add rebootdays? or change endTime to 02:00 ?

**Comment by kingdonb** [comment]
If you set `rebootDays` to an empty array, my expectation from reading over the `timewindow` package is that you will effectively disable the reboot. If you have configured alerts to warn you when reboot is required and kured is not able to reboot the hosts, then you should receive an alert when the amount of time reboot has been required has crossed the threshold.

**Comment by Scorito-Dev** [comment]
I read this as no rebootDays = any day is a reboot day, I will try this out, we will find out tonight!

**Comment by kingdonb** [comment]
Based on a commit I pushed to [this branch](https://github.com/kingdonb/kured/tree/test-disable-emptydays), I can say for sure the empty "days" string will result in a timewindow which does not include any days, and not the inverse.

Here is the test case, it's easier to read in context next to a different example that does include some days:

https://github.com/kingdonb/kured/commit/90e8e7946b640ec700697d08c55d00d497998138#diff-af2679b458ccfa149d7ecebd4e458117c1215fcab03e5446b20ab0f41fae70aaR22-R29

**Comment by SimeonPoot** [comment]
Hi there, just out of curiosity, what is the status of this issue? 
If setting no days to disable rebooting is a solution, perhaps a good idea to add this to the tests? 
Kind regards

**Comment by evrardjp** [comment]
I believe we have other tools for "blocking" reboots, but feel free to comment if the current features aren't enough.

**Comment by Scorito-Dev** [comment]
Using the following command we successfully disabled kured

kubectl -n kube-system annotate ds kured weave.works/kured-node-lock='{"nodeID":"manual"}'

**Comment by chawleejay** [comment]
@Scorito-Dev question. to reenable kured do you set '{"nodeID":"manual"}' -> '{"nodeID":"automatic"}'? and then kured will take into account the rebootDays field?
