### ISSUE TITLE
Kured blocking reboot on pending alerts

### ISSUE THREAD

**Issue by codestalkerr** [weaveworks/kured#393]
I have been struggling with the auto rebooting nodes using Kured coz of pending alerts which is not an issue for us.
Since we have so many alerts it comes and goes from pending state randomly and blocks Kured most of the time.

Suggestion: It would be better to just block on "Firing Alerts" or an option to set if we want to block on "Firing Alert" or "Pending Alert" or both.

**Comment by MattJeanes** [comment]
I have raised PR #410 to add this feature as I would like this too 😄

**Comment by codestalkerr** [comment]
> I have raised PR #410 to add this feature as I would like this too 😄

That's Awesome, can't wait to see this out in action 🕺
