### ISSUE TITLE
helm dependency update not working

### ISSUE THREAD

**Issue by preo2nd** [weaveworks/kured#395]
apiVersion: v1 
name: mekured
description: A Helm chart for Kubernetes

type: application

version: 0.1.0

appVersion: "1.7.0"

dependencies:
  - name: kured
    version: 2.4.3
    repo: https://weaveworks.github.io/kured
  
  Error: 
Update Complete. ⎈Happy Helming!⎈
Error: directory charts/kured not found

I have tried manually creating the charts folder and Kured folder but that doesn't work either
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Dependency kured did not declare a repository. Assuming it exists in the charts directory
Error: Unable to load chart: Chart.yaml file is missing

I tried segregating the Dependency into a requirements.yaml file but that didn't work either same errors

helm template aaa .      from a location where the following files and folders are available. tho I have tried charts. Created charts and then even created kured folder to solve the issue.

<img width="342" alt="Screen Shot 2021-06-18 at 2 02 33 PM" src="https://user-images.githubusercontent.com/86124837/122600764-4343d200-d03e-11eb-8b87-e337aefc8817.png">

**Comment by dholbach** [comment]
Can you try https://github.com/weaveworks/kured/tree/main/charts/kured#readme?

The `helm/charts` repo was archived.

**Comment by preo2nd** [comment]
closing issue malformed Chart.yaml key "repo" is suppose to be "repository"
