### ISSUE TITLE
Kured can reboot before end of upgrade

### ISSUE THREAD

**Issue by jfcoz** [weaveworks/kured#403]
Kured check the /var/run/reboot-restarted file.

It is possible that dpkg create this file before the end of an upgrade, so kured can reboot the node during the upgrade.

After the reboot, dpkg can be in the state :

`E: dpkg was interrupted, you must manually run 'dpkg --configure -a' to correct the problem.`

The more you reduce the `--period` check interval, the more risk you have to get this problem.

I think kured should also check that the upgrade process is finished before rebooting the node.

**Comment by evrardjp** [comment]
I think it's fair, but how do you propose to do it in a system agnostic way?
Do you want to take different approaches based on the distro?
Or do you want to ensure the user defines its own way?
