### ISSUE TITLE
/sbin/systemctl not found in AKS

### ISSUE THREAD

**Issue by kautish** [weaveworks/kured#404]
we recently created new AKS cluster (version 1.20.5) and kured 1.7.0. reboot-sentinel and reboot-command were as per default.

Kured monitor newly created node and finds node needs reboot. 

During process of reboot, kured indicates two kind of issues:
* PDB of some pods preventing restart of pods
* reboot command is used and the default version is /sbin/systemctl. AKS seems to have systemctl in /bin and not in /sbin folder.
* reboot command passed as command line parameter does not show "reboot-command" in ARGS field of daemonset configuration

Question:
* Is it correct the default command /sbin/systemctl will not work in AKS? Neither AKS nor kured clearly document this part.
* Why does kured not show same issue in existing clusters (i.e. where kured is an upgrade and not new installation)

Thanks.

**Comment by jackfrancis** [comment]
@alexeldeib can you confirm that AKS nodes need to use a custom reboot command string (kured default is `/sbin/systemctl reboot`)?

@kautish can you provide more details about PodDisruptionBudget issues? Also, you can definitely overrite the reboot command string, either by overriding the `--reboot-comand` option in the daemonset spec if you're doing things manually, or by using the helm config `configuration.rebootCommand` if you're using the official kured helm chart.

**Comment by kautish** [comment]
@jackfrancis 

We are using official kured helm chart for installing app version 1.7.0. The default chart version from repo is 2.7.0.
After adding --reboot-command = /bin/systemctl, we were able to avoid issues on AKS cluster.

The problem of reboot-command did not exist in 1.6.1 app version.

For PDB issue - the error message looks like : 
"error when evicting pods/"cordons-xxxxxxxx-yyyy -n kube-system (will retry after 5 secs). Cannot evict pod as it would violate the pod's disruption budget"

The above error seems to be affecting all pods drained node.

Apparently, kured keeps trying to drain node every 1 hour causing cluster to remain un-usable.

Thanks!

**Comment by alexeldeib** [comment]
@jackfrancis huh, that seems to be the case. I'm a bit surprised since we have docs on using kured and I can't imagine this changed recently...

**Comment by alexeldeib** [comment]
this is a helm chart issue: https://github.com/weaveworks/kured/blob/7a2b4a6a1a007e87ca15e009a8453e8266d65161/charts/kured/values.yaml#L34

in kured code, the default has been the same for a long time: https://github.com/weaveworks/kured/blob/7a2b4a6a1a007e87ca15e009a8453e8266d65161/cmd/kured/main.go#L129

which works just fine on AKS

**Comment by alexeldeib** [comment]
xref: https://github.com/weaveworks/kured/pull/394#issuecomment-880941336
