### ISSUE TITLE
kured pods are not restarted on helm upgrade

### ISSUE THREAD

**Issue by kingdonb** [weaveworks/kured#413]
I've just upgraded my kured from 2.7.0 to 2.7.1 chart version, after fixing the issue described in #404 and #408 and, after some experimenting, I think kured pods need to be restarted in order to take in the new configuration, but that doesn't seem to happen.

I traced around looking to see why that is, and I see that you place labels in the chart templates to be used as a helper, and that winds up looking like this in the kured daemonset:

```
template:
  metadata:
    labels:
      app: kured
      chart: kured-2.7.0
      heritage: Helm
      release: kured
```

So I upgraded from one chart version to the next and it updated the template labels, and I expected this to restart all of my kured pods, but it did not.

I found this line in values.yaml:

https://github.com/weaveworks/kured/blob/24f4925b3f085091cfeff5335c50c4de70b9be9d/charts/kured/values.yaml#L7-L9

That's handy... DaemonSet do not have RollingUpdate as a default strategy. I went tracing around in history and found that comment was added in this commit: https://github.com/weaveworks/kured/commit/d4893d7bd705e2fbe4950d375a82685d9e65f4a6

It seems like a sensible default to me. I tried setting `updateStrategy: RollingUpdate` and it worked exactly according to my expectations. Should we just make it the default in the next version of Kured charts?

**Comment by dholbach** [comment]
@ckotzbauer WDYT?

**Comment by dholbach** [comment]
Or @davidkarlsen maybe?

**Comment by ckotzbauer** [comment]
yes, +1 for changing the default-strategy to "RollingUpdate". This was sth. we just took over from the old chart at helm/charts.

**Comment by davidkarlsen** [comment]
> Or @davidkarlsen maybe?

It makes sense to have it as rolling by default.

**Comment by ckotzbauer** [comment]
@kingdonb Do you want to open a PR for that?
