### ISSUE TITLE
Push image to a different registry, in addition to Docker Hub

### ISSUE THREAD

**Issue by onedr0p** [weaveworks/kured#421]
**Is your feature request related to a problem? Please describe.**

Dockerhub rate limits

**Describe the solution you'd like**

Push kured to an additional registry like Quay or GHCR

**Comment by dholbach** [comment]
```cli
Run docker/login-action@v1
Logging into quay.io...
Error: Error response from daemon: Get "https://quay.io/v2/": unauthorized: This user has been disabled. Please contact your administrator.
```
Not quite solved yet.

**Comment by dholbach** [comment]
→ https://github.com/orgs/weaveworks/packages/container/package/kured
