### ISSUE TITLE
Support drain timeout in Helm chart

### ISSUE THREAD

**Issue by jamesrcounts** [weaveworks/kured#435]
I'm working with a team that is using the helm chart for deployment.  They are very interested in the drain-timeout feature mentioned in the main readme. 

```
      --drain-timeout duration              timeout after which the drain is aborted (default: 0, infinite time)
```

However, it looks like the helm chart has not been updated to support this option.  I'm familiar with Helm and it looks straightforward to add, would you be open to a pull request for this?

**Comment by ckotzbauer** [comment]
There is a open PR to add those flags. #360
We will try to merge this as soon as possible. I will close this in the meantime.
