### ISSUE TITLE
Using cronlike pattern

### ISSUE THREAD

**Issue by mbaykara** [weaveworks/kured#452]
Is it possible to use a cron pattern like `0 12-18 28-31 * 6` running kured once a month? #feature

**Comment by ckotzbauer** [comment]
No, this is currently not possible, since there are multiple parameters (start-time, end-time, reboot-days) to control the kured reboot-times. A cron-line syntax would only be possible with an additional parameter.

**Comment by mbaykara** [comment]
Thanks for the response!
