### ISSUE TITLE
Notifications to Microsoft Teams

### ISSUE THREAD

**Issue by tgarlot** [weaveworks/kured#47]
Hi,

I would like to use Microsoft Teams instead of Slack for drain/reboot notification. Implementation would be a lot similar as it's also using a simple webhook with a custom JSON structure.

Would you accept a PR for that? 

thanks

**Comment by strowi** [comment]
would be very interested in this..

**Comment by strowi** [comment]
at least for MSTeam it just works if you put the Teams-webhook for  "--slack-hook-url=..."

**Comment by mmisztal1980** [comment]
What's the status of #49 ? A lot of ppl could really use it by now.

 Can it be added and the generic impl be postponed till somebody has the actual time to do it?

**Comment by PeterUherek** [comment]
Hey guys, what is a state of this feature?

**Comment by mirageglobe** [comment]
did anyone have MS teams webhook work for --slack-hook-url? tried using extraargs with MS teams webhook and it did not like it. no errors and did not trigger notification even thou reboot-required file was present.

**Comment by dsargent3220** [comment]
Would also like to send notifications to Teams.  Tried to use the slack URL and it didn't work.  If someone knows a way to make this work, please share here.  :)

**Comment by tarioch** [comment]
It works for me I have set the slack hook url to the incoming webhook url of my teams channel.
