### ISSUE TITLE
Deployment Options

### ISSUE THREAD

**Issue by thepaulmacca** [weaveworks/kured#470]
I'm quite new to kured and was wondering how people were deploying this, helm charts or the kured daemon set YAMl file?

I'm leaning towards helm, but does anyone have any examples that they could share? This is for AKS and using Flux

Thanks

**Comment by ckotzbauer** [comment]
Hi @thepaulmacca,
thanks for your question. It's up to you if you will use the helm-chart or plain YAMLs to deploy kured to your cluster.

For the helm-chart please read the instructions [here](https://github.com/weaveworks/kured/tree/main/charts/kured#installing-the-chart). All config-options are described in the table below.

When you want to use YAMLs you can download it from the Github-Release (For the latest kured release this would be: https://github.com/weaveworks/kured/releases/download/1.8.0/kured-1.8.0-dockerhub.yaml)

**Comment by thepaulmacca** [comment]
Thanks for replying, I'll probably go down the helm chart route so I can have different config per environment. Will see how it goes!

**Comment by dholbach** [comment]
And maybe join us in the #kured Channel on Weave Slack (https://slack.weave.works) for further questions.

**Comment by thepaulmacca** [comment]
Will do, thanks!
