### ISSUE TITLE
More documentation about pulling lots of kured images from container registry

### ISSUE THREAD

**Issue by jackfrancis** [weaveworks/kured#471]
Because kured is a daemonset, during large cluster scale out events, it's likely that pulling many container image pulls at the same time will induce throttling from the image registry provider. Let's call that out in docs, and suggest how to work around that (e.g., pre-pulling kured images in the node OS image so that the container image is in the node host OS's local registry cache).

**Comment by evrardjp** [comment]
(or have your own company registry / local cache with kured image in)
