### ISSUE TITLE
Weird running number added from extraArgs list

### ISSUE THREAD

**Issue by anattapol** [weaveworks/kured#477]
Hi,

I upgrade kured helm with extraArgs like this
```bash
helm upgrade -i --kube-context="$context" --namespace "kube-system" \
  --force \
  --set extraArgs={period=0h0m30s} \
  --wait --timeout '5m0s' \
  kured kured/kured --dry-run
```

I got `0=` generated infront of my list of args
```yaml
          args:
            - --ds-name=kured
            - --ds-namespace=kube-system
            - --reboot-command=/bin/systemctl reboot
            - --0=period=0h0m30s
 ```

**Comment by ckotzbauer** [comment]
For me it worked, when using `--set extraArgs.period=0h0m30s`. Can you confirm this?

**Comment by anattapol** [comment]
hi @ckotzbauer ,

Yes, that works for me. the way of extraArgs={} helps us to configure as dynamic as possible which includes and manage the option as List in helm standard.
```bash
helm upgrade -i --kube-context="$context" --namespace "kube-system" \
  --force \
  --set 'extraArgs={period=0h0m30s,foo=bar,far=blue}' \
  --wait --timeout '5m0s' \
  kured kured/kured --dry-run
```

Currently it produce,
```yaml
          args:
            - --ds-name=kured
            - --ds-namespace=kube-system
            - --reboot-command=/bin/systemctl reboot
            - --0=period=0h0m30s
            - --1=foo=bar
            - --2=far=blue
 ```

**Comment by ckotzbauer** [comment]
Yes, but I think is is more a helm-related topic than one from the kured chart. You can use the `--set extraArgs.xyz=abc` multiple times:
```
helm upgrade -i --kube-context="$context" --namespace "kube-system" \
  --force \
  --set 'extraArgs.period=0h0m30s' \
  --set 'extraArgs.foo=bar' \
  --set 'extraArgs.far=blue' \
  --wait --timeout '5m0s' \
  kured kured/kured --dry-run
```
So the command can be very dynamic too.

**Comment by anattapol** [comment]
@ckotzbauer , 
Thank you for your support.
FYI, the guideline https://github.com/weaveworks/kured/tree/main/charts/kured#configuration to follow {} approach.

**Comment by ckotzbauer** [comment]
> FYI, the guideline https://github.com/weaveworks/kured/tree/main/charts/kured#configuration to follow {} approach.

That's just the default-value and not the approach to use. But maybe this is not clear enough.
