### ISSUE TITLE
Option to allow reboots only in a time window

### ISSUE THREAD

**Issue by EPinci** [weaveworks/kured#48]
Hello there,

as a possible feature, can you add an option so that reboots can be constrained in a specific time window?
This way I would be able to have the reboots, let's say, happening only at night time.

Thank you

**Comment by DaveAurionix** [comment]
Potentially limiting these to one day in the week would be useful too, in order to avoid rebooting too often.  Limiting reboots to overnight would be a great first step though.

**Comment by lunarfs** [comment]
Guess this should be solved by https://github.com/weaveworks/kured/pull/20/#pullrequestreview-123935393 "adding option to skip rebooting during weekends" The title is a bit missleading as the pullrequest allows you to specify days where it will not rebot the nodes

**Comment by lunarfs** [comment]
> @lunarfs This use-case for this issue is restricting reboots to night time, so I guess #20 is not really applicable, unless it is generalized even more.

You are right. My bad.

**Comment by jcassee** [comment]
@lunarfs Would you consider generalizing #20 even more to include this use-case as well? :smile:

**Comment by lunarfs** [comment]
> @lunarfs Would you consider generalizing #20 even more to include this use-case as well? smile

so something like --allow-reboot=11:30-17:30 ?

**Comment by jcassee** [comment]
I was thinking about something that would either match `days-to-exclude` or would supersede it. Some ideas:

#### Match `days-to-exclude`

I think `times-to-exclude` would be the logical equivalent name. For example:

* Only reboot during office hours: `--days-to-exclude=saturday,sunday --times-to-exclude=17:00-9:00`
* Only reboot during night-time: `--times-to-exclude=6:00-0:00`

Or use positive naming:
* Only reboot during office hours: `--allow-days=monday,tuesday,wednesday,thursday,friday --allow-times=9:00-17:00`.
* Only reboot during night-time: `--allow-times=0:00-6:00`

Not that times crossing day boundaries would have to be supported in both cases.

#### Supersede `days-to-exclude`

For example:

* Only reboot during office hours: `--reboot-window=mon,tue,wed,thu,fri@9:00-17:00`
* Only reboot during night-time: `--reboot-window=*@0:00-6:00`

Such an option could be used multiple times to give multiple reboot windows. Does some kind of "time period parser" exist in the Go ecosystem?

Of course, with expressiveness comes complexity, and I am not sure anyone needs it. 

What do you think?

**Comment by kfox1111** [comment]
What about a crontab format? It is used in kubernetes already in cronjob.

**Comment by jcassee** [comment]
@kfox1111 Yeah, but can the cronjob describe periods?

**Comment by jcassee** [comment]
Nice, that could actually work!

**Comment by DaveAurionix** [comment]
I'm not sure a cronjob will work.  Is that example a 9-5 continuous range or is it once an hour between 9 and 5 at discrete hourly intervals?  I ask because Kured could check for a reboot-required file at intervals but if it cannot obtain a lock, should it reboot as soon as it can (at any time/day) or should it wait and try again at the next discrete interval (risking not being able to reboot at all if another hourly event blocks it) or should it reboot as soon as it can but only within a given time slot of 9-5 (probably the desired option but not what the cronjob format can describe)?

**Comment by DaveAurionix** [comment]
If five servers are trying to reboot, for example, and they all race to obtain a lock at 9am, how would that play out in practice?  Are we happy for reboots to be over five hours, one server per hour (in the hourly cronjob example given above)?

**Comment by kfox1111** [comment]
Its just time pattern:

```
* 9,10,11,12,13,14,15,16,17 * * MON,WED,FRI
```
that you can match against.

The first star is, match any minute. The next field is match only if one of the hours that is specified, any numeric month day, any month, only on mondays wendnesdays and fridays.

You can do stuff like, match only every other hour, */2, etc.

It could also be used as a frequency for how often you kick off your reboot test passes, but doesn't have to be.

https://crontab.guru/ is a nice website to play around with some of the possibilities.

I think it should probably be a time right before the reboot. So, lock is granted, time pattern is checked against current time. If it doesnt match, no good, try again later. If it does, reboot?

Perhaps a splay time is what your interested in? Keep a random value up to the specified splay per host, and match that against the pattern too? I thought there was a master server picking which node to reboot next though. is that not the case? (I'm new here)

**Comment by lunarfs** [comment]
I think the cron option is an excellent suggestion, it would also solve our issue in https://github.com/weaveworks/kured/pull/20 I will try to look into the code today and see if it makes sence to do a Pullrequest.

**Comment by theharleyquin** [comment]
Super excited to see the outcome of this also.

**Comment by voidengineer** [comment]
Any news on this?

**Comment by mleneveut** [comment]
Any update ? We can't used kured in production without this feature.

**Comment by DaveAurionix** [comment]
@mleneveut As a workaround whilst we wait, at GivePenny we release a Kubernetes deployment on a schedule once per week that deploys Kured at a certain time, then another automated release 2hrs later that deletes the k8s deployment (removes Kured).  That keeps our reboots to a controlled day-of-week and time window.  By accident it also saves a little reserved RAM and CPU outside of those periods.  Might only be a useful workaround if you have a means to schedule automated releases (we use Azure DevOps).

**Comment by MiyKh** [comment]
A possible workaround can be to set a cronjob to disable the reboot on each node and delete the annotation only in the time window

**Comment by EliasKnutsson** [comment]
Any progress on this? Really needed future for us in order to use it in Production env.

**Comment by DaveAurionix** [comment]
@stealthybox Really appreciate the work done on Kured, it seems the best automated node reboot agent for Kubernetes and we really depend on it for applying security patches - thank you.

Thanks also for merging the pull request for this issue into master (#66) - do you know roughly when a Release might be coming out that includes this work?

**Comment by dholbach** [comment]
https://github.com/weaveworks/kured/releases/tag/1.3.0 has been released and includes #66.
