### ISSUE TITLE
Enable manual restarts of nodes

### ISSUE THREAD

**Issue by Uvindu96** [weaveworks/kured#488]
As per the documentation, currently kured restarts the pods automatically if `/var/run/reboot-required` file is exists. Is there any mechanism to override this approach ?, The requirement is if we don't need to restart the node right now, and we need to hold it until we are ready, or we need to reschedule the node restart for another time? Can we do that using kured ? **I'm looking for solution like hold the automatic restart or reschedule it for another time.**

**Comment by ckotzbauer** [comment]
Repost my answers given in slack:

- **Rescheduling** to another time is not possible, as reboots are not "scheduled" directly. Instead they are only allowed at a certain time-window you set globally to kured (reboot-days, start-time, end-time, time-zone). You can of course configure kured to reboot at any time (from 0:00 to 23:59) and control the reboot-time by yourself with one of the blocking-mechanisms described above.
- **Block a node from reboot:** This is possible in two different ways: You can configure a Prometheus-Alert (alert-filter-regexp) which should not fire in case the reboot should be done. Another possibility is to configure a "blocking-pod-selector" and ensure that there's always a pod running on a particular node, as long as you don't want to reboot that node.
- **Notifications:** There are no notifications when there is only a pending-reboot which has not actually started from kured.
