### ISSUE TITLE
Support node readiness labels

### ISSUE THREAD

**Issue by liger1978** [weaveworks/kured#509]
The Zalando PostgreSQL Operator depends on node readiness labels to schedule pods on nodes.  To trigger a failover of the "leader" role in the PostgreSQL Patroni HA cluster from one pod to another in the event of a node reboot, a label must be updated on the node before it is cordoned and drained. The label must be updated once more after the node is rebooted and uncordened.

Would you accept a PR to optionally update node readiness labels before and after the reboot process?

**Comment by evrardjp** [comment]
It makes sense to me.

**Comment by liger1978** [comment]
@ckotzbauer @evrardjp
