### ISSUE TITLE
a daemon to reboot after some time

### ISSUE THREAD

**Issue by guilhem** [weaveworks/kured#51]
Just a simple information to let you know that I created a daemon to reboot after some uptime.
https://github.com/barpilot/kured-toujours
It's really simple and alpha for now, but it can be useful for some people.

It's mainly used to reboot periodically every node and avoid some deadlock with docker, mounts… with the power of _kured_.

**Comment by evrardjp** [comment]
@guilhem thanks for the info. I suppose that if you really want to maintain your `kured-toujours`, we could document it in this repo...

@dholbach I think we can close this one now.

**Comment by dholbach** [comment]
We are starting kured dev meeting now (first to start in 35 mins, 16:00 UTC) today. This might be short notice, but maybe you want to come to one of the next ones and present your solution there: https://docs.google.com/document/d/1bsHTjHhqaaZ7yJnXF6W8c89UB_yn-OoSZEmDnIP34n8/edit# and we can see if we add a *Integrations* section on the main README some time

**Comment by guilhem** [comment]
Hi
Yes _kured-toujours_ works right now (it's really simple as I said).
I may have to update some part of it, but as I didn't receive any issues... :)

Sorry I didn't join the meeting, I've seen it too late.

Best Regards

**Comment by dholbach** [comment]
We'll do it on a monthly cadence, we're also on #kured Slack (https://slack.weave.works/ for the invite).
