### ISSUE TITLE
Vulnerabilities in weaveworks/kured:1.9.2 

### ISSUE THREAD

**Issue by KR411-prog** [weaveworks/kured#522]
[1mScan results for: image weaveworks/kured:1.9.2 sha256:bffdade0693b71564996b664b0d07e09fa21ffab7f123b9789a6d2b329622b73[0m
[1mVulnerabilities[0m
+----------------+----------+------+---------+---------+--------------------------+------------+------------+----------------------------------------------------+
| [1m     CVE      [0m | [1mSEVERITY[0m | [1mCVSS[0m | [1mPACKAGE[0m | [1mVERSION[0m | [1m         STATUS         [0m | [1mPUBLISHED [0m | [1mDISCOVERED[0m | [1m                   DESCRIPTION                    [0m |
+----------------+----------+------+---------+---------+--------------------------+------------+------------+----------------------------------------------------+
| [0mCVE-2022-27191[0m | [91;1mhigh[0m     | [0m7.50[0m | [0mgo[0m      | [0m1.16.14[0m | [0mfixed in 0.0.0[0m           | [0m14 days[0m    | [0m< 1 hour[0m   | [0mgolang.org/x/crypto/ssh before[0m                     |
|                |          |      |         |         | 14 days ago              |            |            | 0.0.0-20220314234659-1baeb1ce4c0b in Go through    |
|                |          |      |         |         |                          |            |            | 1.16.15 and 1.17.x through 1.17.8 allows an        |
|                |          |      |         |         |                          |            |            | attacker to crash a server ...                     |
+----------------+----------+------+---------+---------+--------------------------+------------+------------+----------------------------------------------------+
| [0mCVE-2022-24921[0m | [91;1mhigh[0m     | [0m7.50[0m | [0mgo[0m      | [0m1.16.14[0m | [0mfixed in 1.17.8, 1.16.15[0m | [0m27 days[0m    | [0m< 1 hour[0m   | [0mregexp.Compile in Go before 1.16.15 and 1.17.x[0m     |
|                |          |      |         |         | 27 days ago              |            |            | before 1.17.8 allows stack exhaustion via a deeply |
|                |          |      |         |         |                          |            |            | nested expression.                                 |
+----------------+----------+------+---------+---------+--------------------------+------------+------------+----------------------------------------------------+
| [0mCVE-2021-29923[0m | [91;1mhigh[0m     | [0m7.50[0m | [0mgo[0m      | [0m1.16.14[0m | [0mfixed in 1.17[0m            | [0m> 7 months[0m | [0m< 1 hour[0m   | [0mGo before 1.17 does not properly consider[0m          |
|                |          |      |         |         | > 7 months ago           |            |            | extraneous zero characters at the beginning of     |
|                |          |      |         |         |                          |            |            | an IP address octet, which (in some situations)    |
|                |          |      |         |         |                          |            |            | allows attack...                                   |
+----------------+----------+------+---------+---------+--------------------------+------------+------------+----------------------------------------------------+

[1mVulnerabilities found for image weaveworks/kured:1.9.2: total - 3, critical - 0, high - 3, medium - 0, low - 0[0m
[1mVulnerability threshold check results: PASS[0m

[1mCompliance Issues[0m
+----------+------------------------------------------------------------------------+
| [1mSEVERITY[0m | [1m                             DESCRIPTION                              [0m |
+----------+------------------------------------------------------------------------+
| [91;1mhigh[0m     | [0m(CIS_Docker_v1.2.0 - 4.1) Image should be created with a non-root user[0m |
+----------+------------------------------------------------------------------------+

[1mCompliance found for image weaveworks/kured:1.9.2: total - 1, critical - 0, high - 1, medium - 0, low - 0[0m
[1mCompliance threshold check results: PASS[0m

**Comment by ckotzbauer** [comment]
Please see #511 for that. I close this as duplicate.
