### ISSUE TITLE
Broken Helm chart with Kubernetes v1.24

### ISSUE THREAD

**Issue by elchenberg** [weaveworks/kured#542]
When I use the chart with Kubernetes v1.24 the resulting DaemonSet YAML is broken:

```yaml
        tolerations:- key: node-role.kubernetes.io/control-plane
            effect: NoSchedule
```

I suspect that the second minus in line 178 is causing this issue by removing one newline too much:

```
          {{- if ge .Capabilities.KubeVersion.Minor "24" -}}
```

<https://github.com/weaveworks/kured/blob/main/charts/kured/templates/daemonset.yaml#L178>

Helm version: 3.8.1
Kubernetes version: 1.24.0

**Comment by ckotzbauer** [comment]
Thanks for opening the issue. Would you mind opening a PR for this?
