### ISSUE TITLE
Maintenance mode feature

### ISSUE THREAD

**Issue by johnwc** [weaveworks/kured#546]
It would be nice to have a feature added that would allow a node to be just shutdown and/or not be 'uncordon' when it boots back up. We run our k8s in vsphere, and sometimes we need to make changes to the VMs config that requires the VM to be powered off.

Maybe look for a `/var/run/maintenance-required` file, that requires to be manually removed to put the node back online.

**Comment by jackfrancis** [comment]
@johnwc can you take a look at this project of mine and remark upon how well it solves your use-case?

https://github.com/jackfrancis/kustodian

The above is essentially a copy/pasta of kured with the node reboot parts removed and maintenance put in.

My thinking behind scaffolding that experiment is that "node maintenance" tooling, in practice, is probably too different from "automatic node rebooting" tooling and should be its own thing.

But I'd love to hear your thoughts if you have time to mess around a bit. I have a bias towards "do one thing well" which also explains why I'm inclined towards separating these bits of functionality.

If you think there's a viable path forward for kured evolution to include node maintenance conveniences do let us know!

**Comment by johnwc** [comment]
Can you create a release/vx.x.x branch or a stable branch? That way I can only point to that branch, and only PR to it when there is known stable updates. I don't want to use the main branch that you seem to use while development.

**Comment by jackfrancis** [comment]
@johnwc I've created a v0.0.1 branch here:

https://github.com/jackfrancis/kustodian/tree/release-v0.0.1

I'll try to make time to cut an actual release this week, but no functional. changes will be applied to the above branch if you'd like to use it reliably.
