### ISSUE TITLE
Prometheus SSL/TLS certificate

### ISSUE THREAD

**Issue by yosri-ben-mahfoudh** [weaveworks/kured#55]
Hello,

I was wondering if there is a way to specify prometheus ssl certificates a long with prometheus-url. Actually, kured is encountring the following error when trying to contact Promehtues:

kured-2wksk kured time="2018-12-27T09:04:02Z" level=warning msg="Reboot blocked: prometheus query error: Get https://monitoring-prometheus:9090/api/v1/query?query=ALERTS&time=2018-12-27T09%3A04%3A02.438586828Z: x509: certificate signed by unknown authority"

**Comment by zeeZ** [comment]
Try mounting your CA certificate from a Secret or ConfigMap as `/etc/ssl/certs/ca-certificates.crt` or another one of the paths listed here:
https://golang.org/src/crypto/x509/root_linux.go

**Comment by evrardjp** [comment]
IMO, this can be closed. @dholbach could you press the button, please? :D

**Comment by dholbach** [comment]
Ok. We'll close this one for now. Please reopen if necessary.
