### ISSUE TITLE
Start time option

### ISSUE THREAD

**Issue by johnwc** [weaveworks/kured#555]
Is there a way to have the scheduler have a start time? So that we can tell it something like midnight is the start time, so that when the period is set to 15m it checks every 15 minutes on the hour. (2:00, 2:15, 2:45, 3:00, 3:15, etc...) Instead of every 15 minutes from when the service daemon started.

**Comment by ckotzbauer** [comment]
No, there's no cron-like behaviour possible right now. See #452 for a similar request. What would be the usecase for that different behaviour?

**Comment by johnwc** [comment]
Mainly so that as we are going about our day and need to reboot a node, we know when the next scheduled time should be. Being able to go do something else while we wait till then.

**Comment by atighineanu** [comment]
Does this solve your issue?
https://github.com/weaveworks/kured/pull/566

**Comment by johnwc** [comment]
No, and I don't think I'd want to edit config just to reboot a node.
