### ISSUE TITLE
Do i need to mount systemd ?

### ISSUE THREAD

**Issue by Shikaz** [weaveworks/kured#567]
I am not sure how this will use systemctl reboot ? do i need to mount systemd ?

**Comment by ckotzbauer** [comment]
No, we run the commands within a `nsenter` context.

**Comment by Shikaz** [comment]
@ckotzbauer - Thanks for your reply, is there a way to debug or try to test it from inside the kured pod ? as i don't see any of the nodes being rebooted although they show in the logs "time to reboot"

**Comment by Shikaz** [comment]
Thanks again @ckotzbauer 
So I try with:
nsenter --mount=/proc/1/ns/mnt -- shutdown ....etc

**Comment by Shikaz** [comment]
Was able to test whatever I wanted, thanks to @ckotzbauer , closing the issue
