### ISSUE TITLE
(Optionally?) Notify when node is up and running again

### ISSUE THREAD

**Issue by Alxandr** [weaveworks/kured#585]
I have a 3-node system which I'm currently evaluating (before putting it to actual use) - and I've had an issue where every now and again (once a month or so) one of the nodes fails to boot properly (nothing to do with kured itself). However, a good way I discover this is that it's been a while since the nodes last rebooted (kured posts this to a slack channel I check every-so-often). Mostly, this is good enough, cause the nodes reboot nightly due to updates - but sometimes there are a few days between updates and I have to go check if the nodes are actually running. It would be really great if kured could simply also send a notification once the kured daemon is up and running again on the rebooted node.

**Comment by atighineanu** [comment]
I am addressing in a bigger patch something really close, I can easily implement this if @ckotzbauer @dholbach would agree that we need it.

**Comment by ckotzbauer** [comment]
Hi @Alxandr,
thanks for this idea. Yes, I think it would be good to have an option for another message when the uncordon is successful after the reboot. With this you can have up to three messages per node:
1. Start draining
2. Start reboot
3. Uncordon finished

@atighineanu Feel free to open a PR for that 😉 👍 
@Alxandr Apart from that, this message could improve the detection of failed reboots, but this is something which has to be handled from a cluster monitoring too.

**Comment by atighineanu** [comment]
> Hi @Alxandr, thanks for this idea. Yes, I think it would be good to have an option for another message when the uncordon is successful after the reboot. With this you can have up to three messages per node:
> 
> 1. Start draining
> 2. Start reboot
> 3. Uncordon finished
> 
> @atighineanu Feel free to open a PR for that 😉 👍 @Alxandr Apart from that, this message could improve the detection of failed reboots, but this is something which has to be handled from a cluster monitoring too.

The only 5 cents I'd like to add to the functionality above is: 4. If the node.Unschedulable (after reboot) for some time => Inform about it somewhere.

**Comment by Alxandr** [comment]
> Apart from that, this message could improve the detection of failed reboots, but this is something which has to be handled from a cluster monitoring too.

Yes, ofcause. However, this is a new cluster I'm currently just evaluating the hardware/software stack (which includes things like using kured etc.). It's not currently used for anything (important), and probably won't be for another 3-6 months. Before I start putting anything I care about on it, I will have monitoring in place.

**Comment by atighineanu** [comment]
@Alxandr, here you go: https://github.com/weaveworks/kured/pull/587

**Comment by Alxandr** [comment]
Great. Will this be released as a new version (including helm?) - or do I need to build it myself?

**Comment by ckotzbauer** [comment]
I think we can do a patch release in the next few days.
