### ISSUE TITLE
kured is not cordoning aks nodes

### ISSUE THREAD

**Issue by vivuu1989** [weaveworks/kured#586]
we are using aks private cluster of version 1.22.6 enabled with AzureCNI type. Andd our nodepools are using the image version as below.

    Name       NodeImageVersion
    ---------  ---------------------------------------
    devpool   AKSUbuntu-1804gen2containerd-2022.02.07
    system     AKSUbuntu-1804gen2containerd-2022.02.07

So we introduced kured installation to manage the nodes image update in a scheduled way and followed the document to install the components. https://anchortagdev.com/schedule-azure-kubernetes-service-aks-cluster-updates-with-kured/

verified that all components are created and the kured daemonset pods are running in all nodes.

below is the the yaml got by kubect edit command for the kured daemonset

    apiVersion: apps/v1
    kind: DaemonSet
    metadata:
      annotations:
        deprecated.daemonset.template.generation: "6"
      name: kured
      namespace: kube-system
    spec:
      revisionHistoryLimit: 10
      selector:
        matchLabels:
          name: kured
      template:
        metadata:
          labels:
            name: kured
        spec:
          containers:
          - command:
            - /usr/bin/kured
            - --period=1m
            - --start-time=10am
            - --end-time=1pm
            - --time-zone=Local
            - --ds-name=kured
            - --ds-namespace=kube-system
            - --reboot-days=mon
            env:
            - name: KURED_NODE_ID
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            image: docker.io/weaveworks/kured:master-f6e4062
            imagePullPolicy: IfNotPresent
            name: kured
            resources: {}
            securityContext:
              privileged: true
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          hostPID: true
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          serviceAccount: kured
          serviceAccountName: kured
          terminationGracePeriodSeconds: 30
          tolerations:
          - effect: NoSchedule
            key: node-role.kubernetes.io/master
      updateStrategy:
        rollingUpdate:
          maxSurge: 0
          maxUnavailable: 1
        type: RollingUpdate

But eventhough we made the period to 1 minute, the nodes are still showing as "Ready for Scheduling" and we expected this should be cordoned by the kured automatically as its having outdated image and verified that the /var/run/reboot-required files is existing in all these niodes.

below is the output from the deaemon set pods.

    time="2022-06-24T09:24:12Z" level=info msg="Kubernetes Reboot Daemon: master-f6e4062"
    time="2022-06-24T09:24:12Z" level=info msg="Node ID: aks-devpool-1xxxxxxx-vmssxxxxxxx"
    time="2022-06-24T09:24:12Z" level=info msg="Lock Annotation: kube-system/kured:weave.works/kured-node-lock"
    time="2022-06-24T09:24:12Z" level=info msg="Reboot Sentinel: /var/run/reboot-required every 1m0s"
    time="2022-06-24T09:24:12Z" level=info msg="Blocking Pod Selectors: []"
    time="2022-06-24T09:24:12Z" level=info msg="Reboot on: ---Mon--------------- between 10:00 and 13:00 UTC"

**Comment by jackfrancis** [comment]
@vivuu1989 You are only allowing a 3 hour time window each week for reboots. If kured detects that you are not in that time window it will not do any work:

https://github.com/weaveworks/kured/blob/1.10.0/cmd/kured/main.go#L677

See the continue here:

https://github.com/weaveworks/kured/blob/1.10.0/cmd/kured/main.go#L680

I've linked to the 1.10.0 release; I'm not sure if this behavior has changed recently, so I believe it applies generally.

**Comment by vivuu1989** [comment]
I didn't get you completely. What's my understanding is lured will check the existence of the reboot-required file in every minutes and will cordon the node if it exists regardless of the reboot window. But in this case, eventhough the nodes has these files already existing the jured is not cordoning or marking the node as non-scheduled ,. I guess it's not related to the reboot window

**Comment by jackfrancis** [comment]
@vivuu1989 you don't actually want kured to do that. That would mean the following:

1. On Tuesday, a new automated patch upgrade is delivered to all nodes which requires a reboot
2. kured notices this and marks all nodes as Unschedulable
3. No new pods are able to be scheduled onto any nodes for 6 days
4. kured reboots the nodes during the reboot window

You only want to mark nodes as Unschedulable, and then drain existing pods, if you are able to anticipate that the node is going offline in the near future. So it's sane (IMO) that kured does those prepatory actions only if the configured reboot window is active.

Does that make sense?

**Comment by vivuu1989** [comment]
@jackfrancis .. Sorry That I am still confused about this. I will try to make my question as simple . So my understanding about the kured functioning is as below and  please correct me if i am wrong.

" kured checks for the existence of /var/run/reboot-required as per the propert we set "--period" and for testing purpose now I set to  every  minutes.  in my case  since the nodes are alredy out dated ( last update happened on feb) and "reboot-required" file already existing, the nodes will mark ad "Unschedilable", that means these nodes wont be getting any new pods scheduled to it. Then according to the reboot window we set [In my case  every week Monday 10AM to 1 pm] it will perform the draiing activity.  But when I tested, the kured is not making any noded "Unschedulable" eventhough it has the reboot-requird file existing. So you meant kured will notice the nodes which are required reboot only during active reboot window?

**Comment by jackfrancis** [comment]
> kured checks for the existence of /var/run/reboot-required as per the propert we set "--period"

Kured does not do the above if you are not in the configured time window.

**Comment by vivuu1989** [comment]
Thanks for clarifying
