### ISSUE TITLE
run script

### ISSUE THREAD

**Issue by kfox1111** [weaveworks/kured#59]
Some updates that can happen need to happen after the node is drained to not effect workload. (some kinds of docker upgrades for example)

So the procedure might be:
1. detect upgrades, flag node
2. controller sees flag, drains node
3. upgrades applied on the node
4. reboot
5. controller uncordons

Can a hook on the node agent be added to run a script before reboot but after drain?

**Comment by evrardjp** [comment]
I am not sure we should keep this issue open... Kured **is** about rebooting :)
Though I suspect that for your case, having a configurable restart command could do the trick?

**Comment by kfox1111** [comment]
vm's tend to reboot quick so making the distinction between reboot and just restarting services that were updated probably doesn't help much.

On bare metal though, bios's can take 5-10 minutes to post in some cases. On a larger cluster this adds up. Being able to override the reboot to skip it if unneeded or wire in a kexec to bypass the bios could really benefit users of this type of cluster.

Yeah, I think the ability to just override the reboot command might be enough.

**Comment by evrardjp** [comment]
Awesome, thanks!

**Comment by evrardjp** [comment]
@dholbach we can probably close this for now, as we can track it in #122 .

**Comment by dholbach** [comment]
Maybe we can collect use-cases and stories in #122 so we can make sure we target them all and have e.g docs and tests where applicable too?

**Comment by evrardjp** [comment]
Yup that sounds fine for me. I thought just pointing to the appropriate PRs there would be enough, but if you want to summarize, feel free! :p

**Comment by stuartpb** [comment]
I'll note that Kubic has `kexec` as an alternative reboot implementation to `kured`: https://kubic.opensuse.org/documentation/man-pages/transactional-update.conf.5.html
