### ISSUE TITLE
kured in AKS throwing error

### ISSUE THREAD

**Issue by vivuu1989** [weaveworks/kured#590]
we are using aks private cluster of version 1.22.6 enabled with AzureCNI type. We introduced kured installation to manage the nodes image update in a scheduled way and followed the document to install the components. https://anchortagdev.com/schedule-azure-kubernetes-service-aks-cluster-updates-with-kured/

verified that all components are created and the kured daemonset pods are running in all nodes.

below is the the yaml got by kubect edit command for the kured daemonset

    apiVersion: apps/v1
    kind: DaemonSet
    metadata:
      annotations:
        deprecated.daemonset.template.generation: "6"
      name: kured
      namespace: kube-system
    spec:
      revisionHistoryLimit: 10
      selector:
        matchLabels:
          name: kured
      template:
        metadata:
          labels:
            name: kured
        spec:
          containers:
          - command:
            - /usr/bin/kured
            - --period=1m
            - --start-time=10am
            - --end-time=1pm
            - --time-zone=Local
            - --ds-name=kured
            - --ds-namespace=kube-system
            - --reboot-days=mon
            env:
            - name: KURED_NODE_ID
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            image: docker.io/weaveworks/kured:master-f6e4062
            imagePullPolicy: IfNotPresent
            name: kured
            resources: {}
            securityContext:
              privileged: true
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          hostPID: true
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          serviceAccount: kured
          serviceAccountName: kured
          terminationGracePeriodSeconds: 30
          tolerations:
          - effect: NoSchedule
            key: node-role.kubernetes.io/master
      updateStrategy:
        rollingUpdate:
          maxSurge: 0
          maxUnavailable: 1
        type: RollingUpdate

we made the period to 1 minute, to test the behavior and we are getting below error

```
time="2022-06-26T13:41:04Z" level=info msg="Kubernetes Reboot Daemon: master-f6e4062"
time="2022-06-26T13:41:04Z" level=info msg="Node ID: aksxxxxxxxxxxxxxxxxxxx"
time="2022-06-26T13:41:04Z" level=info msg="Lock Annotation: kube-system/kured:weave.works/kured-node-lock"
time="2022-06-26T13:41:04Z" level=info msg="Reboot Sentinel: /var/run/reboot-required every 1m0s"
time="2022-06-26T13:41:04Z" level=info msg="Blocking Pod Selectors: []"
time="2022-06-26T13:41:04Z" level=info msg="Reboot on: Sun------------Fri--- between 13:00 and 18:00 UTC"
time="2022-06-26T13:42:10Z" level=info msg="Reboot required"
time="2022-06-26T13:42:10Z" level=fatal msg="Error acquiring lock: daemonsets.apps \"kured\" is forbidden: User \"system:serviceaccount:kube-system:kured\" cannot update resource \"daemonsets\" in API group \"apps\" in the namespace \"kube-system\""
```

**Comment by ckotzbauer** [comment]
Hi @vivuu1989,
the rbac permissions from the blog post are not correct anymore for the daemonset and your cluster version. Please refer to the official docs for a new installation of a stable version: https://github.com/weaveworks/kured#installation
