### ISSUE TITLE
Does Kured help in updating the AKS node OS images of type Availability sets?

### ISSUE THREAD

**Issue by smartaquarius10** [weaveworks/kured#591]
Team,

We have AKS cluster v1.23.5 with nodes of type Availability sets. Does kured help in updating these node images for security patches/updates. 

We tried updating them using azure cli with a flag **--node-image-only** but getting an error because we don't have virtual machine scale set.

```diff
- This cluster is not using VirtualMachineScaleSets. Node image upgrade only operation can only be applied on VirtualMachineScaleSets cluster
```
Please let me know if Kured can help in this case.. We are facing lot of vulnerability challenges since many months and we have to resolve them asap.. Would really appreciate your support.

Thank you

**Comment by ckotzbauer** [comment]
Hi @smartaquarius10,
I'm not familiar with AKS and how nodes and clusters should be updated there. Kured is "only" a cloud-agnostic reboot-daemon, so the patching of the Nodes has to be done elsewhere. Kured only reboots the nodes if this is needed.

**Comment by smartaquarius10** [comment]
@ckotzbauer , Oh ok.. So this can only reboot.. I thought it can install updates and patches as well..

**Comment by ckotzbauer** [comment]
Nope, sorry 😉 
Maybe @jackfrancis has a quick answer for the update-strategy in AKS.

**Comment by jackfrancis** [comment]
I think the bullet points in the Introduction here provide a nice definitive set of kured functionality:

https://github.com/weaveworks/kured#introduction

**Comment by smartaquarius10** [comment]
@jackfrancis, Hmm ok.. Actually there are lot of vulnerabilities coming due to OS patches.. Now, its like a do or die situation.. I'm exploring different areas that how can we update the nodes. I don't know why microsoft has given 2 different types of option (availability sets **&** virtual machine scale sets)  for nodes when its not possible to update Availability sets.

**Comment by jackfrancis** [comment]
@smartaquarius10 there are a lot of ways to do this, it's impossible to summarize guidance. In any event kured is scoped to only reboot (Linux) nodes, it does nothing else.

If you prefer the open source route, have you opened an issue at https://github.com/Azure/AKS/issues/new/choose ?

**Comment by jackfrancis** [comment]
Sure, install a hostNetwork-enabled daemonset that runs the following:

```
#!/bin/sh
apt-get -f -y install
apt-get update
unattended_upgrade
```

**Comment by jackfrancis** [comment]
Given all that... I don't advise you do any of this. :)

Essentially what you're doing is running the commands on the node OS itself. There are lots of ways to do this. The above is a Kubernetes-idiomatic approach for folks comfortable in that realm.

I would advise you pick a vector that you are comfortable with running arbitrary commands on all your nodes. If you aren't comfortable with that, I would advise you reach out to AKS support.

**Comment by smartaquarius10** [comment]
@jackfrancis, Oh ok.. Understood. I think so for me its kind of a pretty risky.. Can I login the nodes using this command

`$ kubectl debug node/aks-nodepool1-12345678-vmss000000 -it --image=mcr.microsoft.com/dotnet/runtime-deps:6.0`

As given here
https://docs.microsoft.com/en-us/azure/aks/node-access

And then manually run the command which you've specified.. Will that be ok

**Comment by jackfrancis** [comment]
The above would indeed do the trick for a single node (though I don't know how automatable that is).

**Comment by smartaquarius10** [comment]
@jackfrancis , I just need to do it for once.. After this I will switch to VMSS for sure..

I'll try this for once. I don't know if this will also work on Availability sets because the example given in docs is again with VMSS.. By any chance is it possible to reach out to u in case I stuck somewhere.. Or I would be grateful to you if you don't close this question so that I can reach out to here.. If that works?

**Comment by smartaquarius10** [comment]
@jackfrancis, I logged into the node.. These are the details coming. 

> DISTRIB_ID=Ubuntu
> DISTRIB_RELEASE=18.04
> DISTRIB_CODENAME=bionic
> DISTRIB_DESCRIPTION="Ubuntu 18.04.6 LTS"
> NAME="Ubuntu"
> VERSION="18.04.6 LTS (Bionic Beaver)"
> ID=ubuntu
> ID_LIKE=debian
> PRETTY_NAME="Ubuntu 18.04.6 LTS"
> VERSION_ID="18.04"
> HOME_URL="https://www.ubuntu.com/"
> SUPPORT_URL="https://help.ubuntu.com/"
> BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
> PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
> VERSION_CODENAME=bionic
> UBUNTU_CODENAME=bionic

Is there any command to check whether it has the latest updates or not. Like can I see these details

![image](https://user-images.githubusercontent.com/7824529/176156698-f1fdad9f-70b6-4973-9465-398b54d641c9.png)

**Comment by jackfrancis** [comment]
@smartaquarius10 To be respectful to the kured community, let's close this issue and move discussion elsewhere. This content can pollute search requests for folks investigating behaviors in kured specifically, which this thread doesn't cover.

**Comment by smartaquarius10** [comment]
@jackfrancis , I'm extremely sorry for this..

**Comment by jackfrancis** [comment]
@smartaquarius10 All good, hopefully you're moving in the right direction! ❤️

**Comment by smartaquarius10** [comment]
@jackfrancis, This is my last message in kured community. Sorry for flooding. But I really wanted to appreciate you and kured community for all the help. 

You are genius, awesome.. Seriously. You can't imagine. How much you've helped me.. Infinity times Thanks to you.. Would be grateful if you can help me a little more. Really grateful.. I've pinged you in [AKS question](https://github.com/Azure/AKS/issues/3027)
