### ISSUE TITLE
Identify nodes rebooted by kured

### ISSUE THREAD

**Issue by bobbyfisherman** [weaveworks/kured#603]
I am using kured and it works well but I am wondering if there is a way to know that nodes have been rebooted by kured and not by something else?
I can see the rebooted nodes in prometheus by looking at uptime but I don't know if those have happened because of kured or not.
I see there is a bunch of flag to add labels but I don't see if that could help. I am not using any notification to a chat system, it would be great to see this through prometheus

**Comment by jackfrancis** [comment]
Hi @bobbyfisherman,

The best way at present is to use this facility:

https://github.com/weaveworks/kured/pull/296

Essentially, by including `--set configuration.annotateNodes=true` (using the helm CLI usage as an example) when you install the kured helm chart you will get the following annotations on nodes that are touched by kured:

When a node is currently being rebooted by kured:

- `weave.works/kured-reboot-in-progress`

After a node has successfully rebooted:

- `weave.works/kured-most-recent-reboot-needed`

Those annotations will have a timestamp as the value, so you know _when_ things occurred (and the in-progress annotation is deleted after the node has rebooted).

Will that help?

**Comment by bobbyfisherman** [comment]
@jackfrancis I saw that PR but I thought it was removed in the latest release since the flag isn't documented in the repo README as far as I can tell, but I see it present in the chart.
Thank you!

**Comment by jackfrancis** [comment]
@bobbyfisherman that's totally understandable, updating the README here:

https://github.com/weaveworks/kured/pull/607
