### ISSUE TITLE
Get alerts via icinga API?

### ISSUE THREAD

**Issue by omerlh** [weaveworks/kured#61]
Proposal: Allow to pass icinga URL and host/service for alerts. Kured will query icinga API and if there is an active alert on the specific host/service - the node will not be rebooted.

Useful for users (like us) who use icinga/nagios for monitoring.

**Comment by evrardjp** [comment]
I suppose this could be implemented in a similar fashion as https://github.com/weaveworks/kured/blob/834e7d191d029c733930eb561e3f40ace470d8a3/cmd/kured/main.go#L153-L167 .

**Comment by evrardjp** [comment]
Though I am afraid people will just come with different solutions... Does someone have an idea on how to make this generic? Webhooks?
