### ISSUE TITLE
smtp notifications not working with startTLS

### ISSUE THREAD

**Issue by urbaman** [weaveworks/kured#611]
Hi,

I'm struggling to use the smtp notify system.

I'm using a simple URL:

smtp://user@domain.com:password@smtpdomain.com:587/?fromAddress=kured@domain.com&toAddresses=user@domain.com

The smtp server is a Plesk system behind Cloudflare DNS (not proxied).

I tried changing the ssl cert of the mail server, both with letsencrypt and cloudflare certs, but I get "the cert is not valid for smtp.domain.com" or "the cert is signed by invalid authority".

Using other clients to the same smtp works, enabling "accept all certs", is there a way to properly make this work?

Thank you very much.

**Comment by ckotzbauer** [comment]
Hi @urbaman,
as we use shoutrrr under the hood, maybe you have to post your question to their repo: https://github.com/containrrr/shoutrrr
Kured only passes the URL to shoutrrr and it does the notification then.

**Comment by urbaman** [comment]
Thank you very much, I'll try there.

**Comment by ckotzbauer** [comment]
Ref: https://github.com/containrrr/shoutrrr/issues/265

Please feel free to comment or reopen if kured has to do something.
