### ISSUE TITLE
Error: unknown flag: --blocking-pod-selector

### ISSUE THREAD

**Issue by yosbeleg89** [weaveworks/kured#62]
I have configured a Flag: `--blocking-pod-selector=runtime=long` to prevent kured to reboot some pods when running (according to the [documentation](https://github.com/weaveworks/kured/blob/master/README.md#blocking-reboots-via-pods)), now Kured pods are in a `CrashLoopBackOff` status and the logs are:

```
Error: unknown flag: --blocking-pod-selector
Usage:
  kured [flags]

Flags:
      --alert-filter-regexp regexp.Regexp   alert names to ignore when checking for active alerts
      --ds-name string                      name of daemonset on which to place lock (default "kured")
      --ds-namespace string                 namespace containing daemonset on which to place lock (default "kube-system")
  -h, --help                                help for kured
      --lock-annotation string              annotation in which to record locking node (default "weave.works/kured-node-lock")
      --period duration                     reboot check period (default 1h0m0s)
      --prometheus-url string               Prometheus instance to probe for active alerts
      --reboot-sentinel string              path to file whose existence signals need to reboot (default "/var/run/reboot-required")
      --slack-hook-url string               slack hook URL for reboot notfications
      --slack-username string               slack username for reboot notfications (default "kured")

time="2019-03-07T16:57:24Z" level=fatal msg="unknown flag: --blocking-pod-selector"
```

Which shows like the flag isn't supported. I'm using version `1.1.0` of kured.

**Comment by tbauers** [comment]
If you check out the source and compare the `1.1.0` tag to master you will notice that the selector isn't supported. To be able to use that flag you will need to build source and create your own container image. I just hit the same problem in my setup and stumbled on your issue trying to troubleshoot. Hope this helps!

https://github.com/weaveworks/kured/blob/1.1.0/cmd/kured/main.go

**Comment by yosbeleg89** [comment]
Thanks @tbauers for let me know that. I will go with that option if there is no plan to release soon an oficial updated release of kured. 

@awh is there an estimated date for a next official release of kured? Thanks

**Comment by awh** [comment]
@yosbeleg89 @tbauers https://github.com/weaveworks/kured/releases/1.2.0
