### ISSUE TITLE
zlib and busybox Vulnerabilities in latest 1.10.1 release (base alpine image)

### ISSUE THREAD

**Issue by sstetlermsft** [weaveworks/kured#622]
Alpine has a security update for zlib and busybox.  Is there going to be a new release / build soon?

**Comment by ckotzbauer** [comment]
Hi, please have a look at existing issues first, before creating new ones.
From #621
> with the next kured release, these CVEs would be fixed automatically. But currently there's no new release planned and we don't rebuild images without release right now.
If these CVEs are important to you and you need a fresh image, you can build it by yourself. It is not pretty easy. See https://github.com/weaveworks/kured/issues/608 for more information.

Closing this as duplicate
