### ISSUE TITLE
kured-1.10.2-dockerhub.yaml not found

### ISSUE THREAD

**Issue by har050277** [weaveworks/kured#624]
Hi,

https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/blob/master/kustomize/kured.yaml is failing because of a missing
 https://github.com/weaveworks/kured/releases/download/1.10.2/kured-1.10.2-dockerhub.yaml

https://github.com/weaveworks/kured/releases/download/1.10.1/kured-1.10.1-dockerhub.yaml is found but not selected

**Comment by ckotzbauer** [comment]
Thanks for the hint, I forgot about the upload. Added it now.
