### ISSUE TITLE
kured is not compatible with rancheros

### ISSUE THREAD

**Issue by malaiwah** [weaveworks/kured#65]
Just in case someone tries the route of trying kured on rancheros and gets those errors:

time="2019-03-15T14:42:22Z" level=warning msg="nsenter: can't execute '/usr/bin/test': No such file or directory" cmd=/usr/bin/nsenter std=err
time="2019-03-15T14:42:52Z" level=warning msg="nsenter: can't execute '/usr/bin/test': No such file or directory" cmd=/usr/bin/nsenter std=err
time="2019-03-15T14:42:52Z" level=info msg="Reboot not required"
time="2019-03-15T14:43:22Z" level=warning msg="nsenter: can't execute '/usr/bin/test': No such file or directory" cmd=/usr/bin/nsenter std=err
time="2019-03-15T14:43:52Z" level=warning msg="nsenter: can't execute '/usr/bin/test': No such file or directory" cmd=/usr/bin/nsenter std=err
time="2019-03-15T14:43:52Z" level=info msg="Reboot not required"
time="2019-03-15T14:44:22Z" level=warning msg="nsenter: can't execute '/usr/bin/test': No such file or directory" cmd=/usr/bin/nsenter std=err

It is because RancherOS has its PID:1 as the system-dockerd, which does not have much inside, and does not have the sentinel file (it would be in the os-console system container)

    1 root     system-dockerd --restart=false --log-opt max-file=2 --log-opt max-size=25m --pidfile /var/run/system-docker.pid --userland-proxy=false --bip 172.18.42.1/16 --config-file /etc/docker/system-docker.json --exec-root /var/run/system-docker --group root --host unix:///var/run/system-docker.sock --graph /var/lib/system-docker --storage-driver overlay2

It would be nice if `kured` supported having an annotation on the node instead to have it rebooted (I know there is one to prevent reboot, but none to force, just the sentinel).

**Comment by laghoule** [comment]
@malaiwah have you found an alternative to Kured for RancherOS?

**Comment by laghoule** [comment]
Found an alternative with: https://github.com/rancher/system-upgrade-controller
I haven't tested yet, but will.

**Comment by laghoule** [comment]
Ok, I have a "fork" that can work with RancherOS/RKE:  https://github.com/laghoule/kured

**Comment by limberger** [comment]
I was able to run on RancherOs with some minor changes.

[https://github.com/limberger/kured](https://github.com/limberger/kured)
