### ISSUE TITLE
Set delay between reboots

### ISSUE THREAD

**Issue by lumi017** [weaveworks/kured#76]
A flag to set delays between reboots should be added. Just like `--period` for checking for sentinel file, we should have something like `--reboot-delay` to specify a time frame between reboots of the nodes which have the sentinel file. A use case I am having is a cluster containing large pods taking 30 min to load. If I let kured do its job, the nodes are restarted too quickly for the pods to recover.

**Comment by sylr** [comment]
Seconded

**Comment by bboreham** [comment]
You could have a Prometheus alert on the not-ready condition, which would then delay further reboots.
This alert could have a special routing so nobody actually gets notified, but kured would see it.
