### ISSUE TITLE
Drain timeout

### ISSUE THREAD

**Issue by sylr** [weaveworks/kured#78]
It would be great to be able to define a timeout for pod eviction.

If drain did not succeed within the timeout kured would stop trying to evict pods and release the lock.

This would be handy when pod disruption budgets does not allow eviction.

Regards.

**Comment by bboreham** [comment]
Still valid

**Comment by bboreham** [comment]
Is it possible to detect the difference between "drain is taking a long time" and "drain will never happen because of pod disruption budget" ?

**Comment by flbla** [comment]
https://github.com/weaveworks/kured/pull/283

**Comment by matthiasritter** [comment]
We'd love to see this implemented too :-)
Will this be merged?

**Comment by evrardjp** [comment]
@flbla @sylr could you have a look at #341 ? I think the current implementation is covering your case. 
However, if it's not, don't hesitate to highlight what we are missing! :)
