### ISSUE TITLE
When Pod Disruption Budget blocks Node draining, no restart is possible

### ISSUE THREAD

**Issue by kinihun** [weaveworks/kured#82]
Currently for a Cluster running Istio, Node draining can be blocked by Kubernetes due to PodDisruptionBudget policy configuration. When this occurs, Kured until the lock timeouts.

Kured should ignore this error and reboot the Node anyway.

`
time="2019-07-24T14:28:47Z" level=warning msg="error when evicting pod \"istio-galley-75466f5dc7-cz7sd\" (will retry after 5s): Cannot evict pod as it would violate the pod's disruption budget." cmd=/usr/bin/kubectl std=err
time="2019-07-24T14:28:52Z" level=warning msg="error when evicting pod \"istio-telemetry-66fbcd998b-ts27t\" (will retry after 5s): Cannot evict pod as it would violate the pod's disruption budget." cmd=/usr/bin/kubectl std=err
time="2019-07-24T14:28:52Z" level=warning msg="error when evicting pod \"istio-sidecar-injector-6f4c67c6cd-62clr\" (will retry after 5s): Cannot evict pod as it would violate the pod's disruption budget." cmd=/usr/bin/kubectl std=err
`

**Comment by awh** [comment]
> Kured should ignore this error and reboot the Node anyway

I'm not sure this is the correct default - presumably one has configured a disruption budget for a reason :smile: But certainly we can have it as an option.

I'd rather avoid parsing the output of `kubectl drain`, so this will have to wait until after we migrate away from embedding `kubectl` to using the [library version of drain](github.com/kubernetes/kubernetes/pull/72827).

**Comment by ChapChap** [comment]
Or else, can kured at least catch this error and handle it by giving up on the reboot of this node and throw an error

**Comment by antoineozenne** [comment]
Same problem for a standard cluster without any service mesh. There are too cases : the pod ("managed" by the PDB) can't be scheluded on another node, so the situation is blocked in this state, or the pod is rescheduled by Kubernetes on another node, but it takes time so Kured timeouts.

**Comment by s-spindler** [comment]
Faced a similar issue but for me the pod could have easily been rescheduled by k8s on another node. The PDB is quite simple and only states that min 1 pod is running. 
@awh I think that it is the correct default. AFAIU when deleting a pod that has a PDB such as mine, k8s will simply make sure that a second pod is running before killing the old one. Maybe I'm not getting PDBs here but my understanding was, that k8s would take care of fulfilling the PDB.
In the end I simply killed the pod by hand and sure enough a second one was spun up before the first one shut down.

**Comment by s-spindler** [comment]
One more thing: if this isn't changed I would expect kured to at least not set the node to `SchedulingDisabled`. ATM the node is basically drained of pods except for the ones with PDBs.

**Comment by evrardjp** [comment]
> One more thing: if this isn't changed I would expect kured to at least not set the node to `SchedulingDisabled`. ATM the node is basically drained of pods except for the ones with PDBs.

Wouldn't drain should be cordoning the node, which effectively makes it 'SchedulingDisabled'?

**Comment by uncycler** [comment]
An other issue related to PDB, when this happended, CPU usage is up to 100% and it fills logs with hundred of error per seconds.

**Comment by uipo78** [comment]
Should this issue be closed?

**Comment by kinihun** [comment]
Yes, please do.

Thanks.
