### ISSUE TITLE
RBAC support

### ISSUE THREAD

**Issue by winjer** [weaveworks/kured#9]
Thanks very much for this, it's really useful.

There doesn't seem to be any RBAC support yet, and it would be useful. It probably needs to run with it's own service account kube-system:kured, and have a role and rolebindings, maybe packaged up as a helm chart?

I'm happy to develop and submit a patch, if you are ok to review it?

**Comment by 3dinfluence** [comment]
There is an open PR to do this.  See #6

**Comment by winjer** [comment]
Thanks, I'll try that out and report back.

**Comment by awh** [comment]
@sabbour would you mind giving https://github.com/weaveworks/kured/releases/tag/1.1.0 a try?

**Comment by evrardjp** [comment]
I think we can close this.
