### ISSUE TITLE
Better project maintenance

### ISSUE THREAD

**Issue by lumi017** [weaveworks/kured#92]
I have noticed a bunch of pull requests fixing multiple issues which are not merged into the project for a while. Is it possible to have a better repo maintenance? Thanks!

**Comment by evrardjp** [comment]
I think @dholbach is working on cleaning things up. If you want to help, please feel free to join other community members squatting the weaveworks slack, kured chan.

@dholbach can you close this one, please?

**Comment by dholbach** [comment]
This might be a bit short notice, but we'll do kured dev meeting in about 40 mins (16:00 UTC) today. Please join if you're interested in helping steer the project. https://docs.google.com/document/d/1bsHTjHhqaaZ7yJnXF6W8c89UB_yn-OoSZEmDnIP34n8/edit#
