### ISSUE TITLE
Issue with Kured and cluster autoscaler running together

### ISSUE THREAD

**Issue by sauryadas** [weaveworks/kured#93]
When the first node reboots, CAS brings up another node to place the pending pods drained and waiting to be scheduled. Once the process of rebooting all nodes is complete, there is this one node that has not been patched with reboots. The process of rebooting nodes and the CAS bringing up a new node that is not patch continues. Do you have any suggestions on how this should work?

**Comment by sylr** [comment]
Personnaly I patch the init script of the new nodes to upgrade the whole system and reboot the nodes if there are updates that require a reboot.

**Comment by mstavrev** [comment]
Hello, @sylr can you point me, please to how you patched the init scripts?
