### ISSUE TITLE
Is kured only working for Linux?

### ISSUE THREAD

**Issue by mathieu-benoit** [weaveworks/kured#96]
If it's the case (and not working with Windows Nodes), is it accurate to add this below in the DS definition?
```
nodeSelector:
        beta.kubernetes.io/os: linux
```

**Comment by rhockenbury** [comment]
Correct.  It does not work on windows server nodes because pod privileged capabilities are not supported on windows.

**Comment by mathieu-benoit** [comment]
Thanks! So I need to use this command below to avoid any failure with Windows Nodes:
`helm install kured stable/kured --set nodeSelector."beta\.kubernetes\.io/os"=linux`
