### ISSUE TITLE
Formal release (to include scheduling changes)?

### ISSUE THREAD

**Issue by nickmcdowall** [weaveworks/kured#97]
Hi,

We would like to make use of the new scheduling flags that were added after version 1.2.0 was released. (We are using kured via the stable helm charts). 

I notice that dockerhub contains a tag 'master-4beddb5' which does contain the scheduling changes however is a new formal version likely to be released soon?

**Comment by evrardjp** [comment]
That would be awesome.

**Comment by dannyherstell** [comment]
Any news about this topic?

**Comment by evenh** [comment]
An update from @weaveworks would be appreciated. Given the number of issues/PRs and low frequency of development, opening up for community maintainers might be an option?

**Comment by LouisKottmann** [comment]
Hello, what is blocking the release of a new version?

**Comment by dholbach** [comment]
Thanks for hanging in there everyone.

We're close! We want to get the following PRs landed still: https://github.com/weaveworks/kured/milestone/1 - any additional testing and feedback is appreciated.

**Comment by evrardjp** [comment]
Which PRs?

**Comment by dholbach** [comment]
The PRs are merged now. We're testing master in our Dev environment. Test feedback from anyone else is appreciated.

**Comment by dholbach** [comment]
1.3.0 is out now: https://github.com/weaveworks/kured/releases/tag/1.3.0 :fireworks:
