### ISSUE TITLE
Slack invalidates webhook in public repos

### ISSUE THREAD

**Issue by solomson** [weaveworks/kured#98]
We've set the attribute  --slack-hook-url in a public Github repo
After we got a new token, Slack auto-detected this and auto-invalidated it.
I can't see any way to set secrets or mount volumes with the Kured chart, so I'm thinking this currently is not possible to do anymore?

Obvious workaround is just to set the attribute outside git, but this works against our GitOps workflow.

**Comment by bboreham** [comment]
Yes, it's a bad idea to put secrets in a public repo.

There is no chart in this repo; perhaps file issues about that where you found it.

You could look into "sealed secrets" which are decrypted on apply.  Still, there needs to be something outside of your public git.

**Comment by evrardjp** [comment]
Agreed with @bboreham . @dholbach should we close this?

**Comment by dholbach** [comment]
Does this come from https://github.com/helm/charts/tree/master/stable/kured?

**Comment by evrardjp** [comment]
I am not sure how it is in the power of kured to change how slack behaves and invalidates token, but maybe I got that wrong...

**Comment by solomson** [comment]
Ok fair enough I should have posted in https://github.com/helm/charts/tree/master/stable/kured

I still think you will also have this problem if someone decides to put their deployment.yml file in git
